#pragma once

#include "grd_key.h"
#include "../grd_win32_api.h"

// stolen from: https://stackoverflow.com/questions/15966642/how-do-you-tell-lshift-apart-from-rshift-in-wm-keydown-events

GRD_DEDUP GRD_WIN_WPARAM grd_map_windows_left_and_right_keys(GRD_WIN_WPARAM wParam, GRD_WIN_LPARAM lParam) {
	u32    scancode = (lParam & 0x00ff0000) >> 16;
	int    extended = (lParam & 0x01000000) != 0;
	switch (wParam) {
		case GRD_WIN_VK_SHIFT:   return MapVirtualKeyW(scancode, GRD_WIN_MAPVK_VSC_TO_VK_EX);
		case GRD_WIN_VK_CONTROL: return extended ? GRD_WIN_VK_RCONTROL : GRD_WIN_VK_LCONTROL;
		case GRD_WIN_VK_MENU:    return extended ? GRD_WIN_VK_RMENU : GRD_WIN_VK_LMENU;
	}
	return wParam;
}

GRD_DEDUP GrdKey grd_map_windows_key(GRD_WIN_WPARAM wParam, GRD_WIN_LPARAM lParam) {
	wParam = grd_map_windows_left_and_right_keys(wParam, lParam);

	#define GRD_KEY_BINDING(from, to) case from: return GrdKey:: to;
	switch (wParam) {
		GRD_KEY_BINDING(GRD_WIN_VK_UP,    UpArrow);
		GRD_KEY_BINDING(GRD_WIN_VK_DOWN,  DownArrow);
		GRD_KEY_BINDING(GRD_WIN_VK_LEFT,  LeftArrow);
		GRD_KEY_BINDING(GRD_WIN_VK_RIGHT, RightArrow);

	#if 0
		GRD_KEY_BINDING(GRD_WIN_VK_SHIFT,    AnyShift);
		GRD_KEY_BINDING(GRD_WIN_VK_CONTROL,  AnyControl);
		GRD_KEY_BINDING(GRD_WIN_VK_MENU,     AnyAlt);
	#endif

		GRD_KEY_BINDING(GRD_WIN_VK_LSHIFT, LeftShift);
		GRD_KEY_BINDING(GRD_WIN_VK_RSHIFT, RightShift);

		GRD_KEY_BINDING(GRD_WIN_VK_LMENU, LeftAlt);
		GRD_KEY_BINDING(GRD_WIN_VK_RMENU, RightAlt);

		GRD_KEY_BINDING(GRD_WIN_VK_LCONTROL, LeftControl);
		GRD_KEY_BINDING(GRD_WIN_VK_RCONTROL, RightControl);

		GRD_KEY_BINDING(GRD_WIN_VK_BACK,   Backspace);
		GRD_KEY_BINDING(GRD_WIN_VK_DELETE, Delete);
		GRD_KEY_BINDING(GRD_WIN_VK_INSERT, Insert);
		GRD_KEY_BINDING(GRD_WIN_VK_RETURN, Enter);
		GRD_KEY_BINDING(GRD_WIN_VK_ESCAPE, Escape);
		GRD_KEY_BINDING(GRD_WIN_VK_TAB,    Tab);
		GRD_KEY_BINDING(GRD_WIN_VK_SPACE,  Space);

		GRD_KEY_BINDING(GRD_WIN_VK_LBUTTON, LMB);
		GRD_KEY_BINDING(GRD_WIN_VK_RBUTTON, RMB);
		GRD_KEY_BINDING(GRD_WIN_VK_MBUTTON, MMB);
		GRD_KEY_BINDING(GRD_WIN_VK_XBUTTON1, Mouse4);
		GRD_KEY_BINDING(GRD_WIN_VK_XBUTTON2, Mouse5);

		GRD_KEY_BINDING(GRD_WIN_VK_F1,  F1);
		GRD_KEY_BINDING(GRD_WIN_VK_F2,  F2);
		GRD_KEY_BINDING(GRD_WIN_VK_F3,  F3);
		GRD_KEY_BINDING(GRD_WIN_VK_F4,  F4);
		GRD_KEY_BINDING(GRD_WIN_VK_F5,  F5);
		GRD_KEY_BINDING(GRD_WIN_VK_F6,  F6);
		GRD_KEY_BINDING(GRD_WIN_VK_F7,  F7);
		GRD_KEY_BINDING(GRD_WIN_VK_F8,  F8);
		GRD_KEY_BINDING(GRD_WIN_VK_F9,  F9);
		GRD_KEY_BINDING(GRD_WIN_VK_F10, F10);
		GRD_KEY_BINDING(GRD_WIN_VK_F11, F11);
		GRD_KEY_BINDING(GRD_WIN_VK_F12, F12);
		GRD_KEY_BINDING(GRD_WIN_VK_F13, F13);
		GRD_KEY_BINDING(GRD_WIN_VK_F14, F14);
		GRD_KEY_BINDING(GRD_WIN_VK_F15, F15);
		GRD_KEY_BINDING(GRD_WIN_VK_F16, F16);
		GRD_KEY_BINDING(GRD_WIN_VK_F17, F17);
		GRD_KEY_BINDING(GRD_WIN_VK_F18, F18);
		GRD_KEY_BINDING(GRD_WIN_VK_F19, F19);
		GRD_KEY_BINDING(GRD_WIN_VK_F20, F20);
		GRD_KEY_BINDING(GRD_WIN_VK_F21, F21);
		GRD_KEY_BINDING(GRD_WIN_VK_F22, F22);
		GRD_KEY_BINDING(GRD_WIN_VK_F23, F23);
		GRD_KEY_BINDING(GRD_WIN_VK_F24, F24);
		
		GRD_KEY_BINDING(GRD_WIN_VK_PRIOR, PageUp);
		GRD_KEY_BINDING(GRD_WIN_VK_NEXT,  PageDown);

		GRD_KEY_BINDING(GRD_WIN_VK_ADD,      NumpadPlus);
		GRD_KEY_BINDING(GRD_WIN_VK_SUBTRACT, NumpadMinus);

		GRD_KEY_BINDING(GRD_WIN_VK_OEM_PLUS,  Plus);
		GRD_KEY_BINDING(GRD_WIN_VK_OEM_MINUS, Minus);

		GRD_KEY_BINDING(GRD_WIN_VK_CANCEL, CtrlBreak);
		GRD_KEY_BINDING(GRD_WIN_VK_CLEAR, Clear);
		GRD_KEY_BINDING(GRD_WIN_VK_PAUSE, Pause);
		GRD_KEY_BINDING(GRD_WIN_VK_CAPITAL, CapsLock);
		
		GRD_KEY_BINDING(GRD_WIN_VK_KANA,   KanaOrHangul);

		GRD_KEY_BINDING(GRD_WIN_VK_JUNJA, Junja);
		GRD_KEY_BINDING(GRD_WIN_VK_FINAL, Final);
		GRD_KEY_BINDING(GRD_WIN_VK_HANJA, HanjaOrKanji);

		GRD_KEY_BINDING(GRD_WIN_VK_CONVERT,    Convert);
		GRD_KEY_BINDING(GRD_WIN_VK_NONCONVERT, NonConvert);
		GRD_KEY_BINDING(GRD_WIN_VK_ACCEPT,     Accept);
		GRD_KEY_BINDING(GRD_WIN_VK_MODECHANGE, ModeChange);

		GRD_KEY_BINDING(GRD_WIN_VK_END, End);
		GRD_KEY_BINDING(GRD_WIN_VK_HOME, Home);

		GRD_KEY_BINDING(GRD_WIN_VK_SELECT, Select);
		GRD_KEY_BINDING(GRD_WIN_VK_PRINT, Print);
		GRD_KEY_BINDING(GRD_WIN_VK_EXECUTE, Execute);
		GRD_KEY_BINDING(GRD_WIN_VK_SNAPSHOT, PrintScreen);
		GRD_KEY_BINDING(GRD_WIN_VK_HELP, Help);

		GRD_KEY_BINDING(GRD_WIN_VK_LWIN, LeftWindows);
		GRD_KEY_BINDING(GRD_WIN_VK_RWIN, RightWindows);
		GRD_KEY_BINDING(GRD_WIN_VK_APPS, Menu);

		GRD_KEY_BINDING(GRD_WIN_VK_SLEEP, Sleep);

		GRD_KEY_BINDING(GRD_WIN_VK_NUMPAD0, Numpad0);
		GRD_KEY_BINDING(GRD_WIN_VK_NUMPAD1, Numpad1);
		GRD_KEY_BINDING(GRD_WIN_VK_NUMPAD2, Numpad2);
		GRD_KEY_BINDING(GRD_WIN_VK_NUMPAD3, Numpad3);
		GRD_KEY_BINDING(GRD_WIN_VK_NUMPAD4, Numpad4);
		GRD_KEY_BINDING(GRD_WIN_VK_NUMPAD5, Numpad5);
		GRD_KEY_BINDING(GRD_WIN_VK_NUMPAD6, Numpad6);
		GRD_KEY_BINDING(GRD_WIN_VK_NUMPAD7, Numpad7);
		GRD_KEY_BINDING(GRD_WIN_VK_NUMPAD8, Numpad8);
		GRD_KEY_BINDING(GRD_WIN_VK_NUMPAD9, Numpad9);

		GRD_KEY_BINDING(GRD_WIN_VK_MULTIPLY,  NumpadMultiply);
		GRD_KEY_BINDING(GRD_WIN_VK_SEPARATOR, Separator);
		GRD_KEY_BINDING(GRD_WIN_VK_DECIMAL,   NumpadDot);
		GRD_KEY_BINDING(GRD_WIN_VK_DIVIDE,    NumpadSlash);

		GRD_KEY_BINDING(GRD_WIN_VK_NUMLOCK,  Numlock);
		GRD_KEY_BINDING(GRD_WIN_VK_SCROLL,   ScrollLock);

		GRD_KEY_BINDING(GRD_WIN_VK_OEM_NEC_EQUAL, NumpadEqual);

		// KEY_BINDING(VK_OEM_FJ_JISHO,   Dictionary);
		GRD_KEY_BINDING(GRD_WIN_VK_OEM_FJ_MASSHOU, UnregisterWord);
		GRD_KEY_BINDING(GRD_WIN_VK_OEM_FJ_TOUROKU, RegisterWord);
		GRD_KEY_BINDING(GRD_WIN_VK_OEM_FJ_LOYA,    LeftOYAYUBI);
		GRD_KEY_BINDING(GRD_WIN_VK_OEM_FJ_ROYA,    RightOYAYUBI);

		GRD_KEY_BINDING(GRD_WIN_VK_BROWSER_BACK,      BrowserBack);
		GRD_KEY_BINDING(GRD_WIN_VK_BROWSER_FORWARD,   BrowserForward);
		GRD_KEY_BINDING(GRD_WIN_VK_BROWSER_REFRESH,   BrowserRefresh);
		GRD_KEY_BINDING(GRD_WIN_VK_BROWSER_STOP,      BrowserStop);
		GRD_KEY_BINDING(GRD_WIN_VK_BROWSER_SEARCH,    BrowserSearch);
		GRD_KEY_BINDING(GRD_WIN_VK_BROWSER_FAVORITES, BrowserFavorites);
		GRD_KEY_BINDING(GRD_WIN_VK_BROWSER_HOME,      BrowserHome);

		GRD_KEY_BINDING(GRD_WIN_VK_VOLUME_MUTE, VolumeMute);
		GRD_KEY_BINDING(GRD_WIN_VK_VOLUME_DOWN, VolumeDown);
		GRD_KEY_BINDING(GRD_WIN_VK_VOLUME_UP,   VolumeUp);
		GRD_KEY_BINDING(GRD_WIN_VK_MEDIA_NEXT_TRACK, MediaNextTrack);
		GRD_KEY_BINDING(GRD_WIN_VK_MEDIA_PREV_TRACK, MediaPreviousTrack);
		GRD_KEY_BINDING(GRD_WIN_VK_MEDIA_STOP,       MediaStop);
		GRD_KEY_BINDING(GRD_WIN_VK_MEDIA_PLAY_PAUSE, MediaPlayPause);
		GRD_KEY_BINDING(GRD_WIN_VK_LAUNCH_MAIL,         LaunchMail);
		GRD_KEY_BINDING(GRD_WIN_VK_LAUNCH_MEDIA_SELECT, LaunchMediaSelect);
		GRD_KEY_BINDING(GRD_WIN_VK_LAUNCH_APP1,         LaunchApp1);
		GRD_KEY_BINDING(GRD_WIN_VK_LAUNCH_APP2,         LaunchApp2);

		GRD_KEY_BINDING(GRD_WIN_VK_OEM_1,      Semicolon);
		GRD_KEY_BINDING(GRD_WIN_VK_OEM_COMMA,  Comma);
		GRD_KEY_BINDING(GRD_WIN_VK_OEM_PERIOD, Dot);
		GRD_KEY_BINDING(GRD_WIN_VK_OEM_2,      Slash);
		GRD_KEY_BINDING(GRD_WIN_VK_OEM_3,      Tilde);

		GRD_KEY_BINDING(GRD_WIN_VK_OEM_4, LeftSquareBracket);
		GRD_KEY_BINDING(GRD_WIN_VK_OEM_5, Backslash);
		GRD_KEY_BINDING(GRD_WIN_VK_OEM_6, RightSquareBracket);
		GRD_KEY_BINDING(GRD_WIN_VK_OEM_7, Quote);
		// GRD_KEY_BINDING(GRD_WIN_VK_OEM_8, @TODO XXXX ignore this key ??);

		GRD_KEY_BINDING(GRD_WIN_VK_OEM_AX, AX);
		// GRD_KEY_BINDING(GRD_WIN_VK_OEM_102, @TODO XXX ); "<>" or "\|" on RT 102-key kbd.
		GRD_KEY_BINDING(GRD_WIN_VK_ICO_HELP, Help);
		GRD_KEY_BINDING(GRD_WIN_VK_ICO_00, ZeroZero);

		GRD_KEY_BINDING(GRD_WIN_VK_PROCESSKEY, Process);
		
		GRD_KEY_BINDING(GRD_WIN_VK_ICO_CLEAR, Clear);

		GRD_KEY_BINDING(GRD_WIN_VK_ATTN,  Attn);
		GRD_KEY_BINDING(GRD_WIN_VK_CRSEL, CrSel);
		GRD_KEY_BINDING(GRD_WIN_VK_EXSEL, ExSel);
		GRD_KEY_BINDING(GRD_WIN_VK_EREOF, EraseEOF);

		GRD_KEY_BINDING(GRD_WIN_VK_PLAY, Play);
		GRD_KEY_BINDING(GRD_WIN_VK_ZOOM, Zoom);

		GRD_KEY_BINDING(GRD_WIN_VK_OEM_CLEAR, Clear);

		// Character keys will be bound here
		default: 
			return (GrdKey) wParam;
	}
	#undef GRD_KEY_BINDING
}
