#pragma once

#include "../reflect.h"

enum class WindowsMessageCode {
	_WM_NULL = 0x0000,
	_WM_CREATE = 0x0001,
	_WM_DESTROY = 0x0002,
	_WM_MOVE = 0x0003,
	_WM_SIZE = 0x0005,
	_WM_ACTIVATE = 0x0006,
	_WM_SETFOCUS = 0x0007,
	_WM_KILLFOCUS = 0x0008,
	_WM_ENABLE = 0x000a,
	_WM_SETREDRAW = 0x000b,
	_WM_SETTEXT = 0x000c,
	_WM_GETTEXT = 0x000d,
	_WM_GETTEXTLENGTH = 0x000e,
	_WM_PAINT = 0x000f,
	_WM_CLOSE = 0x0010,
	_WM_QUERYENDSESSION = 0x0011,
	_WM_QUIT = 0x0012,
	_WM_QUERYOPEN = 0x0013,
	_WM_ERASEBKGND = 0x0014,
	_WM_SYSCOLORCHANGE = 0x0015,
	_WM_ENDSESSION = 0x0016,
	_WM_SHOWWINDOW = 0x0018,
	_WM_CTLCOLOR = 0x0019,
	_WM_WININICHANGE = 0x001a,
	_WM_DEVMODECHANGE = 0x001b,
	_WM_ACTIVATEAPP = 0x001c,
	_WM_FONTCHANGE = 0x001d,
	_WM_TIMECHANGE = 0x001e,
	_WM_CANCELMODE = 0x001f,
	_WM_SETCURSOR = 0x0020,
	_WM_MOUSEACTIVATE = 0x0021,
	_WM_CHILDACTIVATE = 0x0022,
	_WM_QUEUESYNC = 0x0023,
	_WM_GETMINMAXINFO = 0x0024,
	_WM_PAINTICON = 0x0026,
	_WM_ICONERASEBKGND = 0x0027,
	_WM_NEXTDLGCTL = 0x0028,
	_WM_SPOOLERSTATUS = 0x002a,
	_WM_DRAWITEM = 0x002b,
	_WM_MEASUREITEM = 0x002c,
	_WM_DELETEITEM = 0x002d,
	_WM_VKEYTOITEM = 0x002e,
	_WM_CHARTOITEM = 0x002f,
	_WM_SETFONT = 0x0030,
	_WM_GETFONT = 0x0031,
	_WM_SETHOTKEY = 0x0032,
	_WM_GETHOTKEY = 0x0033,
	_WM_QUERYDRAGICON = 0x0037,
	_WM_COMPAREITEM = 0x0039,
	_WM_GETOBJECT = 0x003d,
	_WM_COMPACTING = 0x0041,
	_WM_COMMNOTIFY = 0x0044,
	_WM_WINDOWPOSCHANGING = 0x0046,
	_WM_WINDOWPOSCHANGED = 0x0047,
	_WM_POWER = 0x0048,
	_WM_COPYGLOBALDATA = 0x0049,
	_WM_COPYDATA = 0x004a,
	_WM_CANCELJOURNAL = 0x004b,
	_WM_NOTIFY = 0x004e,
	_WM_INPUTLANGCHANGEREQUEST = 0x0050,
	_WM_INPUTLANGCHANGE = 0x0051,
	_WM_TCARD = 0x0052,
	_WM_HELP = 0x0053,
	_WM_USERCHANGED = 0x0054,
	_WM_NOTIFYFORMAT = 0x0055,
	_WM_CONTEXTMENU = 0x007b,
	_WM_STYLECHANGING = 0x007c,
	_WM_STYLECHANGED = 0x007d,
	_WM_DISPLAYCHANGE = 0x007e,
	_WM_GETICON = 0x007f,
	_WM_SETICON = 0x0080,
	_WM_NCCREATE = 0x0081,
	_WM_NCDESTROY = 0x0082,
	_WM_NCCALCSIZE = 0x0083,
	_WM_NCHITTEST = 0x0084,
	_WM_NCPAINT = 0x0085,
	_WM_NCACTIVATE = 0x0086,
	_WM_GETDLGCODE = 0x0087,
	_WM_SYNCPAINT = 0x0088,
	_WM_NCMOUSEMOVE = 0x00a0,
	_WM_NCLBUTTONDOWN = 0x00a1,
	_WM_NCLBUTTONUP = 0x00a2,
	_WM_NCLBUTTONDBLCLK = 0x00a3,
	_WM_NCRBUTTONDOWN = 0x00a4,
	_WM_NCRBUTTONUP = 0x00a5,
	_WM_NCRBUTTONDBLCLK = 0x00a6,
	_WM_NCMBUTTONDOWN = 0x00a7,
	_WM_NCMBUTTONUP = 0x00a8,
	_WM_NCMBUTTONDBLCLK = 0x00a9,
	_WM_NCXBUTTONDOWN = 0x00ab,
	_WM_NCXBUTTONUP = 0x00ac,
	_WM_NCXBUTTONDBLCLK = 0x00ad,
	_EM_GETSEL = 0x00b0,
	_EM_SETSEL = 0x00b1,
	_EM_GETRECT = 0x00b2,
	_EM_SETRECT = 0x00b3,
	_EM_SETRECTNP = 0x00b4,
	_EM_SCROLL = 0x00b5,
	_EM_LINESCROLL = 0x00b6,
	_EM_SCROLLCARET = 0x00b7,
	_EM_GETMODIFY = 0x00b8,
	_EM_SETMODIFY = 0x00b9,
	_EM_GETLINECOUNT = 0x00ba,
	_EM_LINEINDEX = 0x00bb,
	_EM_SETHANDLE = 0x00bc,
	_EM_GETHANDLE = 0x00bd,
	_EM_GETTHUMB = 0x00be,
	_EM_LINELENGTH = 0x00c1,
	_EM_REPLACESEL = 0x00c2,
	_EM_SETFONT = 0x00c3,
	_EM_GETLINE = 0x00c4,
	_EM_LIMITTEXT = 0x00c5,
	_EM_SETLIMITTEXT = 0x00c5,
	_EM_CANUNDO = 0x00c6,
	_EM_UNDO = 0x00c7,
	_EM_FMTLINES = 0x00c8,
	_EM_LINEFROMCHAR = 0x00c9,
	_EM_SETWORDBREAK = 0x00ca,
	_EM_SETTABSTOPS = 0x00cb,
	_EM_SETPASSWORDCHAR = 0x00cc,
	_EM_EMPTYUNDOBUFFER = 0x00cd,
	_EM_GETFIRSTVISIBLELINE = 0x00ce,
	_EM_SETREADONLY = 0x00cf,
	_EM_SETWORDBREAKPROC = 0x00d0,
	_EM_GETWORDBREAKPROC = 0x00d1,
	_EM_GETPASSWORDCHAR = 0x00d2,
	_EM_SETMARGINS = 0x00d3,
	_EM_GETMARGINS = 0x00d4,
	_EM_GETLIMITTEXT = 0x00d5,
	_EM_POSFROMCHAR = 0x00d6,
	_EM_CHARFROMPOS = 0x00d7,
	_EM_SETIMESTATUS = 0x00d8,
	_EM_GETIMESTATUS = 0x00d9,
	_SBM_SETPOS = 0x00e0,
	_SBM_GETPOS = 0x00e1,
	_SBM_SETRANGE = 0x00e2,
	_SBM_GETRANGE = 0x00e3,
	_SBM_ENABLE_ARROWS = 0x00e4,
	_SBM_SETRANGEREDRAW = 0x00e6,
	_SBM_SETSCROLLINFO = 0x00e9,
	_SBM_GETSCROLLINFO = 0x00ea,
	_SBM_GETSCROLLBARINFO = 0x00eb,
	_BM_GETCHECK = 0x00f0,
	_BM_SETCHECK = 0x00f1,
	_BM_GETSTATE = 0x00f2,
	_BM_SETSTATE = 0x00f3,
	_BM_SETSTYLE = 0x00f4,
	_BM_CLICK = 0x00f5,
	_BM_GETIMAGE = 0x00f6,
	_BM_SETIMAGE = 0x00f7,
	_BM_SETDONTCLICK = 0x00f8,
	_WM_INPUT = 0x00ff,
	_WM_KEYDOWN = 0x0100,
	_WM_KEYFIRST = 0x0100,
	_WM_KEYUP = 0x0101,
	_WM_CHAR = 0x0102,
	_WM_DEADCHAR = 0x0103,
	_WM_SYSKEYDOWN = 0x0104,
	_WM_SYSKEYUP = 0x0105,
	_WM_SYSCHAR = 0x0106,
	_WM_SYSDEADCHAR = 0x0107,
	_WM_UNICHAR = 0x0109,
	_WM_WNT_CONVERTREQUESTEX = 0x0109,
	_WM_CONVERTREQUEST = 0x010a,
	_WM_CONVERTRESULT = 0x010b,
	_WM_INTERIM = 0x010c,
	_WM_IME_STARTCOMPOSITION = 0x010d,
	_WM_IME_ENDCOMPOSITION = 0x010e,
	_WM_IME_COMPOSITION = 0x010f,
	_WM_IME_KEYLAST = 0x010f,
	_WM_INITDIALOG = 0x0110,
	_WM_COMMAND = 0x0111,
	_WM_SYSCOMMAND = 0x0112,
	_WM_TIMER = 0x0113,
	_WM_HSCROLL = 0x0114,
	_WM_VSCROLL = 0x0115,
	_WM_INITMENU = 0x0116,
	_WM_INITMENUPOPUP = 0x0117,
	_WM_SYSTIMER = 0x0118,
	_WM_MENUSELECT = 0x011f,
	_WM_MENUCHAR = 0x0120,
	_WM_ENTERIDLE = 0x0121,
	_WM_MENURBUTTONUP = 0x0122,
	_WM_MENUDRAG = 0x0123,
	_WM_MENUGETOBJECT = 0x0124,
	_WM_UNINITMENUPOPUP = 0x0125,
	_WM_MENUCOMMAND = 0x0126,
	_WM_CHANGEUISTATE = 0x0127,
	_WM_UPDATEUISTATE = 0x0128,
	_WM_QUERYUISTATE = 0x0129,
	_WM_LBTRACKPOINT = 0x0131,
	_WM_CTLCOLORMSGBOX = 0x0132,
	_WM_CTLCOLOREDIT = 0x0133,
	_WM_CTLCOLORLISTBOX = 0x0134,
	_WM_CTLCOLORBTN = 0x0135,
	_WM_CTLCOLORDLG = 0x0136,
	_WM_CTLCOLORSCROLLBAR = 0x0137,
	_WM_CTLCOLORSTATIC = 0x0138,
	_CB_GETEDITSEL = 0x0140,
	_CB_LIMITTEXT = 0x0141,
	_CB_SETEDITSEL = 0x0142,
	_CB_ADDSTRING = 0x0143,
	_CB_DELETESTRING = 0x0144,
	_CB_DIR = 0x0145,
	_CB_GETCOUNT = 0x0146,
	_CB_GETCURSEL = 0x0147,
	_CB_GETLBTEXT = 0x0148,
	_CB_GETLBTEXTLEN = 0x0149,
	_CB_INSERTSTRING = 0x014a,
	_CB_RESETCONTENT = 0x014b,
	_CB_FINDSTRING = 0x014c,
	_CB_SELECTSTRING = 0x014d,
	_CB_SETCURSEL = 0x014e,
	_CB_SHOWDROPDOWN = 0x014f,
	_CB_GETITEMDATA = 0x0150,
	_CB_SETITEMDATA = 0x0151,
	_CB_GETDROPPEDCONTROLRECT = 0x0152,
	_CB_SETITEMHEIGHT = 0x0153,
	_CB_GETITEMHEIGHT = 0x0154,
	_CB_SETEXTENDEDUI = 0x0155,
	_CB_GETEXTENDEDUI = 0x0156,
	_CB_GETDROPPEDSTATE = 0x0157,
	_CB_FINDSTRINGEXACT = 0x0158,
	_CB_SETLOCALE = 0x0159,
	_CB_GETLOCALE = 0x015a,
	_CB_GETTOPINDEX = 0x015b,
	_CB_SETTOPINDEX = 0x015c,
	_CB_GETHORIZONTALEXTENT = 0x015d,
	_CB_SETHORIZONTALEXTENT = 0x015e,
	_CB_GETDROPPEDWIDTH = 0x015f,
	_CB_SETDROPPEDWIDTH = 0x0160,
	_CB_INITSTORAGE = 0x0161,
	_CB_MULTIPLEADDSTRING = 0x0163,
	_CB_GETCOMBOBOXINFO = 0x0164,
	_CB_MSGMAX = 0x0165,
	_WM_MOUSEFIRST = 0x0200,
	_WM_MOUSEMOVE = 0x0200,
	_WM_LBUTTONDOWN = 0x0201,
	_WM_LBUTTONUP = 0x0202,
	_WM_LBUTTONDBLCLK = 0x0203,
	_WM_RBUTTONDOWN = 0x0204,
	_WM_RBUTTONUP = 0x0205,
	_WM_RBUTTONDBLCLK = 0x0206,
	_WM_MBUTTONDOWN = 0x0207,
	_WM_MBUTTONUP = 0x0208,
	_WM_MBUTTONDBLCLK = 0x0209,
	_WM_MOUSELAST = 0x0209,
	_WM_MOUSEWHEEL = 0x020a,
	_WM_XBUTTONDOWN = 0x020b,
	_WM_XBUTTONUP = 0x020c,
	_WM_XBUTTONDBLCLK = 0x020d,
	_WM_MOUSEHWHEEL = 0x020e,
	_WM_PARENTNOTIFY = 0x0210,
	_WM_ENTERMENULOOP = 0x0211,
	_WM_EXITMENULOOP = 0x0212,
	_WM_NEXTMENU = 0x0213,
	_WM_SIZING = 0x0214,
	_WM_CAPTURECHANGED = 0x0215,
	_WM_MOVING = 0x0216,
	_WM_POWERBROADCAST = 0x0218,
	_WM_DEVICECHANGE = 0x0219,
	_WM_MDICREATE = 0x0220,
	_WM_MDIDESTROY = 0x0221,
	_WM_MDIACTIVATE = 0x0222,
	_WM_MDIRESTORE = 0x0223,
	_WM_MDINEXT = 0x0224,
	_WM_MDIMAXIMIZE = 0x0225,
	_WM_MDITILE = 0x0226,
	_WM_MDICASCADE = 0x0227,
	_WM_MDIICONARRANGE = 0x0228,
	_WM_MDIGETACTIVE = 0x0229,
	_WM_MDISETMENU = 0x0230,
	_WM_ENTERSIZEMOVE = 0x0231,
	_WM_EXITSIZEMOVE = 0x0232,
	_WM_DROPFILES = 0x0233,
	_WM_MDIREFRESHMENU = 0x0234,
	_WM_IME_REPORT = 0x0280,
	_WM_IME_SETCONTEXT = 0x0281,
	_WM_IME_NOTIFY = 0x0282,
	_WM_IME_CONTROL = 0x0283,
	_WM_IME_COMPOSITIONFULL = 0x0284,
	_WM_IME_SELECT = 0x0285,
	_WM_IME_CHAR = 0x0286,
	_WM_IME_REQUEST = 0x0288,
	_WM_IMEKEYDOWN = 0x0290,
	_WM_IME_KEYDOWN = 0x0290,
	_WM_IMEKEYUP = 0x0291,
	_WM_IME_KEYUP = 0x0291,
	_WM_NCMOUSEHOVER = 0x02a0,
	_WM_MOUSEHOVER = 0x02a1,
	_WM_NCMOUSELEAVE = 0x02a2,
	_WM_MOUSELEAVE = 0x02a3,
	_WM_CUT = 0x0300,
	_WM_COPY = 0x0301,
	_WM_PASTE = 0x0302,
	_WM_CLEAR = 0x0303,
	_WM_UNDO = 0x0304,
	_WM_RENDERFORMAT = 0x0305,
	_WM_RENDERALLFORMATS = 0x0306,
	_WM_DESTROYCLIPBOARD = 0x0307,
	_WM_DRAWCLIPBOARD = 0x0308,
	_WM_PAINTCLIPBOARD = 0x0309,
	_WM_VSCROLLCLIPBOARD = 0x030a,
	_WM_SIZECLIPBOARD = 0x030b,
	_WM_ASKCBFORMATNAME = 0x030c,
	_WM_CHANGECBCHAIN = 0x030d,
	_WM_HSCROLLCLIPBOARD = 0x030e,
	_WM_QUERYNEWPALETTE = 0x030f,
	_WM_PALETTEISCHANGING = 0x0310,
	_WM_PALETTECHANGED = 0x0311,
	_WM_HOTKEY = 0x0312,
	_WM_PRINT = 0x0317,
	_WM_PRINTCLIENT = 0x0318,
	_WM_APPCOMMAND = 0x0319,
	_WM_HANDHELDFIRST = 0x0358,
	_WM_HANDHELDLAST = 0x035f,
	_WM_AFXFIRST = 0x0360,
	_WM_AFXLAST = 0x037f,
	_WM_PENWINFIRST = 0x0380,
	_WM_RCRESULT = 0x0381,
	_WM_HOOKRCRESULT = 0x0382,
	_WM_GLOBALRCCHANGE = 0x0383,
	_WM_PENMISCINFO = 0x0383,
	_WM_SKB = 0x0384,
	_WM_HEDITCTL = 0x0385,
	_WM_PENCTL = 0x0385,
	_WM_PENMISC = 0x0386,
	_WM_CTLINIT = 0x0387,
	_WM_PENEVENT = 0x0388,
	_WM_PENWINLAST = 0x038f,
	_DDM_SETFMT = 0x0400,
	_DM_GETDEFID = 0x0400,
	_NIN_SELECT = 0x0400,
	_TBM_GETPOS = 0x0400,
	_WM_PSD_PAGESETUPDLG = 0x0400,
	_WM_USER = 0x0400,
	_CBEM_INSERTITEMA = 0x0401,
	_DDM_DRAW = 0x0401,
	_DM_SETDEFID = 0x0401,
	_HKM_SETHOTKEY = 0x0401,
	_PBM_SETRANGE = 0x0401,
	_RB_INSERTBANDA = 0x0401,
	_SB_SETTEXTA = 0x0401,
	_TB_ENABLEBUTTON = 0x0401,
	_TBM_GETRANGEMIN = 0x0401,
	_TTM_ACTIVATE = 0x0401,
	_WM_CHOOSEFONT_GETLOGFONT = 0x0401,
	_WM_PSD_FULLPAGERECT = 0x0401,
	_CBEM_SETIMAGELIST = 0x0402,
	_DDM_CLOSE = 0x0402,
	_DM_REPOSITION = 0x0402,
	_HKM_GETHOTKEY = 0x0402,
	_PBM_SETPOS = 0x0402,
	_RB_DELETEBAND = 0x0402,
	_SB_GETTEXTA = 0x0402,
	_TB_CHECKBUTTON = 0x0402,
	_TBM_GETRANGEMAX = 0x0402,
	_WM_PSD_MINMARGINRECT = 0x0402,
	_CBEM_GETIMAGELIST = 0x0403,
	_DDM_BEGIN = 0x0403,
	_HKM_SETRULES = 0x0403,
	_PBM_DELTAPOS = 0x0403,
	_RB_GETBARINFO = 0x0403,
	_SB_GETTEXTLENGTHA = 0x0403,
	_TBM_GETTIC = 0x0403,
	_TB_PRESSBUTTON = 0x0403,
	_TTM_SETDELAYTIME = 0x0403,
	_WM_PSD_MARGINRECT = 0x0403,
	_CBEM_GETITEMA = 0x0404,
	_DDM_END = 0x0404,
	_PBM_SETSTEP = 0x0404,
	_RB_SETBARINFO = 0x0404,
	_SB_SETPARTS = 0x0404,
	_TB_HIDEBUTTON = 0x0404,
	_TBM_SETTIC = 0x0404,
	_TTM_ADDTOOLA = 0x0404,
	_WM_PSD_GREEKTEXTRECT = 0x0404,
	_CBEM_SETITEMA = 0x0405,
	_PBM_STEPIT = 0x0405,
	_TB_INDETERMINATE = 0x0405,
	_TBM_SETPOS = 0x0405,
	_TTM_DELTOOLA = 0x0405,
	_WM_PSD_ENVSTAMPRECT = 0x0405,
	_CBEM_GETCOMBOCONTROL = 0x0406,
	_PBM_SETRANGE32 = 0x0406,
	_RB_SETBANDINFOA = 0x0406,
	_SB_GETPARTS = 0x0406,
	_TB_MARKBUTTON = 0x0406,
	_TBM_SETRANGE = 0x0406,
	_TTM_NEWTOOLRECTA = 0x0406,
	_WM_PSD_YAFULLPAGERECT = 0x0406,
	_CBEM_GETEDITCONTROL = 0x0407,
	_PBM_GETRANGE = 0x0407,
	_RB_SETPARENT = 0x0407,
	_SB_GETBORDERS = 0x0407,
	_TBM_SETRANGEMIN = 0x0407,
	_TTM_RELAYEVENT = 0x0407,
	_CBEM_SETEXSTYLE = 0x0408,
	_PBM_GETPOS = 0x0408,
	_RB_HITTEST = 0x0408,
	_SB_SETMINHEIGHT = 0x0408,
	_TBM_SETRANGEMAX = 0x0408,
	_TTM_GETTOOLINFOA = 0x0408,
	_CBEM_GETEXSTYLE = 0x0409,
	_CBEM_GETEXTENDEDSTYLE = 0x0409,
	_PBM_SETBARCOLOR = 0x0409,
	_RB_GETRECT = 0x0409,
	_SB_SIMPLE = 0x0409,
	_TB_ISBUTTONENABLED = 0x0409,
	_TBM_CLEARTICS = 0x0409,
	_TTM_SETTOOLINFOA = 0x0409,
	_CBEM_HASEDITCHANGED = 0x040a,
	_RB_INSERTBANDW = 0x040a,
	_SB_GETRECT = 0x040a,
	_TB_ISBUTTONCHECKED = 0x040a,
	_TBM_SETSEL = 0x040a,
	_TTM_HITTESTA = 0x040a,
	_WIZ_QUERYNUMPAGES = 0x040a,
	_CBEM_INSERTITEMW = 0x040b,
	_RB_SETBANDINFOW = 0x040b,
	_SB_SETTEXTW = 0x040b,
	_TB_ISBUTTONPRESSED = 0x040b,
	_TBM_SETSELSTART = 0x040b,
	_TTM_GETTEXTA = 0x040b,
	_WIZ_NEXT = 0x040b,
	_CBEM_SETITEMW = 0x040c,
	_RB_GETBANDCOUNT = 0x040c,
	_SB_GETTEXTLENGTHW = 0x040c,
	_TB_ISBUTTONHIDDEN = 0x040c,
	_TBM_SETSELEND = 0x040c,
	_TTM_UPDATETIPTEXTA = 0x040c,
	_WIZ_PREV = 0x040c,
	_CBEM_GETITEMW = 0x040d,
	_RB_GETROWCOUNT = 0x040d,
	_SB_GETTEXTW = 0x040d,
	_TB_ISBUTTONINDETERMINATE = 0x040d,
	_TTM_GETTOOLCOUNT = 0x040d,
	_CBEM_SETEXTENDEDSTYLE = 0x040e,
	_RB_GETROWHEIGHT = 0x040e,
	_SB_ISSIMPLE = 0x040e,
	_TB_ISBUTTONHIGHLIGHTED = 0x040e,
	_TBM_GETPTICS = 0x040e,
	_TTM_ENUMTOOLSA = 0x040e,
	_SB_SETICON = 0x040f,
	_TBM_GETTICPOS = 0x040f,
	_TTM_GETCURRENTTOOLA = 0x040f,
	_RB_IDTOINDEX = 0x0410,
	_SB_SETTIPTEXTA = 0x0410,
	_TBM_GETNUMTICS = 0x0410,
	_TTM_WINDOWFROMPOINT = 0x0410,
	_RB_GETTOOLTIPS = 0x0411,
	_SB_SETTIPTEXTW = 0x0411,
	_TBM_GETSELSTART = 0x0411,
	_TB_SETSTATE = 0x0411,
	_TTM_TRACKACTIVATE = 0x0411,
	_RB_SETTOOLTIPS = 0x0412,
	_SB_GETTIPTEXTA = 0x0412,
	_TB_GETSTATE = 0x0412,
	_TBM_GETSELEND = 0x0412,
	_TTM_TRACKPOSITION = 0x0412,
	_RB_SETBKCOLOR = 0x0413,
	_SB_GETTIPTEXTW = 0x0413,
	_TB_ADDBITMAP = 0x0413,
	_TBM_CLEARSEL = 0x0413,
	_TTM_SETTIPBKCOLOR = 0x0413,
	_RB_GETBKCOLOR = 0x0414,
	_SB_GETICON = 0x0414,
	_TB_ADDBUTTONSA = 0x0414,
	_TBM_SETTICFREQ = 0x0414,
	_TTM_SETTIPTEXTCOLOR = 0x0414,
	_RB_SETTEXTCOLOR = 0x0415,
	_TB_INSERTBUTTONA = 0x0415,
	_TBM_SETPAGESIZE = 0x0415,
	_TTM_GETDELAYTIME = 0x0415,
	_RB_GETTEXTCOLOR = 0x0416,
	_TB_DELETEBUTTON = 0x0416,
	_TBM_GETPAGESIZE = 0x0416,
	_TTM_GETTIPBKCOLOR = 0x0416,
	_RB_SIZETORECT = 0x0417,
	_TB_GETBUTTON = 0x0417,
	_TBM_SETLINESIZE = 0x0417,
	_TTM_GETTIPTEXTCOLOR = 0x0417,
	_RB_BEGINDRAG = 0x0418,
	_TB_BUTTONCOUNT = 0x0418,
	_TBM_GETLINESIZE = 0x0418,
	_TTM_SETMAXTIPWIDTH = 0x0418,
	_RB_ENDDRAG = 0x0419,
	_TB_COMMANDTOINDEX = 0x0419,
	_TBM_GETTHUMBRECT = 0x0419,
	_TTM_GETMAXTIPWIDTH = 0x0419,
	_RB_DRAGMOVE = 0x041a,
	_TBM_GETCHANNELRECT = 0x041a,
	_TB_SAVERESTOREA = 0x041a,
	_TTM_SETMARGIN = 0x041a,
	_RB_GETBARHEIGHT = 0x041b,
	_TB_CUSTOMIZE = 0x041b,
	_TBM_SETTHUMBLENGTH = 0x041b,
	_TTM_GETMARGIN = 0x041b,
	_RB_GETBANDINFOW = 0x041c,
	_TB_ADDSTRINGA = 0x041c,
	_TBM_GETTHUMBLENGTH = 0x041c,
	_TTM_POP = 0x041c,
	_RB_GETBANDINFOA = 0x041d,
	_TB_GETITEMRECT = 0x041d,
	_TBM_SETTOOLTIPS = 0x041d,
	_TTM_UPDATE = 0x041d,
	_RB_MINIMIZEBAND = 0x041e,
	_TB_BUTTONSTRUCTSIZE = 0x041e,
	_TBM_GETTOOLTIPS = 0x041e,
	_TTM_GETBUBBLESIZE = 0x041e,
	_RB_MAXIMIZEBAND = 0x041f,
	_TBM_SETTIPSIDE = 0x041f,
	_TB_SETBUTTONSIZE = 0x041f,
	_TTM_ADJUSTRECT = 0x041f,
	_TBM_SETBUDDY = 0x0420,
	_TB_SETBITMAPSIZE = 0x0420,
	_TTM_SETTITLEA = 0x0420,
	_MSG_FTS_JUMP_VA = 0x0421,
	_TB_AUTOSIZE = 0x0421,
	_TBM_GETBUDDY = 0x0421,
	_TTM_SETTITLEW = 0x0421,
	_RB_GETBANDBORDERS = 0x0422,
	_MSG_FTS_JUMP_QWORD = 0x0423,
	_RB_SHOWBAND = 0x0423,
	_TB_GETTOOLTIPS = 0x0423,
	_MSG_REINDEX_REQUEST = 0x0424,
	_TB_SETTOOLTIPS = 0x0424,
	_MSG_FTS_WHERE_IS_IT = 0x0425,
	_RB_SETPALETTE = 0x0425,
	_TB_SETPARENT = 0x0425,
	_RB_GETPALETTE = 0x0426,
	_RB_MOVEBAND = 0x0427,
	_TB_SETROWS = 0x0427,
	_TB_GETROWS = 0x0428,
	_TB_GETBITMAPFLAGS = 0x0429,
	_TB_SETCMDID = 0x042a,
	_RB_PUSHCHEVRON = 0x042b,
	_TB_CHANGEBITMAP = 0x042b,
	_TB_GETBITMAP = 0x042c,
	_MSG_GET_DEFFONT = 0x042d,
	_TB_GETBUTTONTEXTA = 0x042d,
	_TB_REPLACEBITMAP = 0x042e,
	_TB_SETINDENT = 0x042f,
	_TB_SETIMAGELIST = 0x0430,
	_TB_GETIMAGELIST = 0x0431,
	_TB_LOADIMAGES = 0x0432,
	_EM_CANPASTE = 0x0432,
	_TTM_ADDTOOLW = 0x0432,
	_EM_DISPLAYBAND = 0x0433,
	_TB_GETRECT = 0x0433,
	_TTM_DELTOOLW = 0x0433,
	_EM_EXGETSEL = 0x0434,
	_TB_SETHOTIMAGELIST = 0x0434,
	_TTM_NEWTOOLRECTW = 0x0434,
	_EM_EXLIMITTEXT = 0x0435,
	_TB_GETHOTIMAGELIST = 0x0435,
	_TTM_GETTOOLINFOW = 0x0435,
	_EM_EXLINEFROMCHAR = 0x0436,
	_TB_SETDISABLEDIMAGELIST = 0x0436,
	_TTM_SETTOOLINFOW = 0x0436,
	_EM_EXSETSEL = 0x0437,
	_TB_GETDISABLEDIMAGELIST = 0x0437,
	_TTM_HITTESTW = 0x0437,
	_EM_FINDTEXT = 0x0438,
	_TB_SETSTYLE = 0x0438,
	_TTM_GETTEXTW = 0x0438,
	_EM_FORMATRANGE = 0x0439,
	_TB_GETSTYLE = 0x0439,
	_TTM_UPDATETIPTEXTW = 0x0439,
	_EM_GETCHARFORMAT = 0x043a,
	_TB_GETBUTTONSIZE = 0x043a,
	_TTM_ENUMTOOLSW = 0x043a,
	_EM_GETEVENTMASK = 0x043b,
	_TB_SETBUTTONWIDTH = 0x043b,
	_TTM_GETCURRENTTOOLW = 0x043b,
	_EM_GETOLEINTERFACE = 0x043c,
	_TB_SETMAXTEXTROWS = 0x043c,
	_EM_GETPARAFORMAT = 0x043d,
	_TB_GETTEXTROWS = 0x043d,
	_EM_GETSELTEXT = 0x043e,
	_TB_GETOBJECT = 0x043e,
	_EM_HIDESELECTION = 0x043f,
	_TB_GETBUTTONINFOW = 0x043f,
	_EM_PASTESPECIAL = 0x0440,
	_TB_SETBUTTONINFOW = 0x0440,
	_EM_REQUESTRESIZE = 0x0441,
	_TB_GETBUTTONINFOA = 0x0441,
	_EM_SELECTIONTYPE = 0x0442,
	_TB_SETBUTTONINFOA = 0x0442,
	_EM_SETBKGNDCOLOR = 0x0443,
	_TB_INSERTBUTTONW = 0x0443,
	_EM_SETCHARFORMAT = 0x0444,
	_TB_ADDBUTTONSW = 0x0444,
	_EM_SETEVENTMASK = 0x0445,
	_TB_HITTEST = 0x0445,
	_EM_SETOLECALLBACK = 0x0446,
	_TB_SETDRAWTEXTFLAGS = 0x0446,
	_EM_SETPARAFORMAT = 0x0447,
	_TB_GETHOTITEM = 0x0447,
	_EM_SETTARGETDEVICE = 0x0448,
	_TB_SETHOTITEM = 0x0448,
	_EM_STREAMIN = 0x0449,
	_TB_SETANCHORHIGHLIGHT = 0x0449,
	_EM_STREAMOUT = 0x044a,
	_TB_GETANCHORHIGHLIGHT = 0x044a,
	_EM_GETTEXTRANGE = 0x044b,
	_TB_GETBUTTONTEXTW = 0x044b,
	_EM_FINDWORDBREAK = 0x044c,
	_TB_SAVERESTOREW = 0x044c,
	_EM_SETOPTIONS = 0x044d,
	_TB_ADDSTRINGW = 0x044d,
	_EM_GETOPTIONS = 0x044e,
	_TB_MAPACCELERATORA = 0x044e,
	_EM_FINDTEXTEX = 0x044f,
	_TB_GETINSERTMARK = 0x044f,
	_EM_GETWORDBREAKPROCEX = 0x0450,
	_TB_SETINSERTMARK = 0x0450,
	_EM_SETWORDBREAKPROCEX = 0x0451,
	_TB_INSERTMARKHITTEST = 0x0451,
	_EM_SETUNDOLIMIT = 0x0452,
	_TB_MOVEBUTTON = 0x0452,
	_TB_GETMAXSIZE = 0x0453,
	_EM_REDO = 0x0454,
	_TB_SETEXTENDEDSTYLE = 0x0454,
	_EM_CANREDO = 0x0455,
	_TB_GETEXTENDEDSTYLE = 0x0455,
	_EM_GETUNDONAME = 0x0456,
	_TB_GETPADDING = 0x0456,
	_EM_GETREDONAME = 0x0457,
	_TB_SETPADDING = 0x0457,
	_EM_STOPGROUPTYPING = 0x0458,
	_TB_SETINSERTMARKCOLOR = 0x0458,
	_EM_SETTEXTMODE = 0x0459,
	_TB_GETINSERTMARKCOLOR = 0x0459,
	_EM_GETTEXTMODE = 0x045a,
	_TB_MAPACCELERATORW = 0x045a,
	_EM_AUTOURLDETECT = 0x045b,
	_TB_GETSTRINGW = 0x045b,
	_EM_GETAUTOURLDETECT = 0x045c,
	_TB_GETSTRINGA = 0x045c,
	_EM_SETPALETTE = 0x045d,
	_EM_GETTEXTEX = 0x045e,
	_EM_GETTEXTLENGTHEX = 0x045f,
	_EM_SHOWSCROLLBAR = 0x0460,
	_EM_SETTEXTEX = 0x0461,
	_TAPI_REPLY = 0x0463,
	_ACM_OPENA = 0x0464,
	_BFFM_SETSTATUSTEXTA = 0x0464,
	_CDM_FIRST = 0x0464,
	_CDM_GETSPEC = 0x0464,
	_EM_SETPUNCTUATION = 0x0464,
	_IPM_CLEARADDRESS = 0x0464,
	_WM_CAP_UNICODE_START = 0x0464,
	_ACM_PLAY = 0x0465,
	_BFFM_ENABLEOK = 0x0465,
	_CDM_GETFILEPATH = 0x0465,
	_EM_GETPUNCTUATION = 0x0465,
	_IPM_SETADDRESS = 0x0465,
	_PSM_SETCURSEL = 0x0465,
	_UDM_SETRANGE = 0x0465,
	_WM_CHOOSEFONT_SETLOGFONT = 0x0465,
	_ACM_STOP = 0x0466,
	_BFFM_SETSELECTIONA = 0x0466,
	_CDM_GETFOLDERPATH = 0x0466,
	_EM_SETWORDWRAPMODE = 0x0466,
	_IPM_GETADDRESS = 0x0466,
	_PSM_REMOVEPAGE = 0x0466,
	_UDM_GETRANGE = 0x0466,
	_WM_CAP_SET_CALLBACK_ERRORW = 0x0466,
	_WM_CHOOSEFONT_SETFLAGS = 0x0466,
	_ACM_OPENW = 0x0467,
	_BFFM_SETSELECTIONW = 0x0467,
	_CDM_GETFOLDERIDLIST = 0x0467,
	_EM_GETWORDWRAPMODE = 0x0467,
	_IPM_SETRANGE = 0x0467,
	_PSM_ADDPAGE = 0x0467,
	_UDM_SETPOS = 0x0467,
	_WM_CAP_SET_CALLBACK_STATUSW = 0x0467,
	_BFFM_SETSTATUSTEXTW = 0x0468,
	_CDM_SETCONTROLTEXT = 0x0468,
	_EM_SETIMECOLOR = 0x0468,
	_IPM_SETFOCUS = 0x0468,
	_PSM_CHANGED = 0x0468,
	_UDM_GETPOS = 0x0468,
	_CDM_HIDECONTROL = 0x0469,
	_EM_GETIMECOLOR = 0x0469,
	_IPM_ISBLANK = 0x0469,
	_PSM_RESTARTWINDOWS = 0x0469,
	_UDM_SETBUDDY = 0x0469,
	_CDM_SETDEFEXT = 0x046a,
	_EM_SETIMEOPTIONS = 0x046a,
	_PSM_REBOOTSYSTEM = 0x046a,
	_UDM_GETBUDDY = 0x046a,
	_EM_GETIMEOPTIONS = 0x046b,
	_PSM_CANCELTOCLOSE = 0x046b,
	_UDM_SETACCEL = 0x046b,
	_EM_CONVPOSITION = 0x046c,
	_MCIWNDM_GETZOOM = 0x046d,
	_PSM_UNCHANGED = 0x046d,
	_UDM_SETBASE = 0x046d,
	_PSM_APPLY = 0x046e,
	_UDM_GETBASE = 0x046e,
	_PSM_SETTITLEA = 0x046f,
	_UDM_SETRANGE32 = 0x046f,
	_PSM_SETWIZBUTTONS = 0x0470,
	_UDM_GETRANGE32 = 0x0470,
	_WM_CAP_DRIVER_GET_NAMEW = 0x0470,
	_PSM_PRESSBUTTON = 0x0471,
	_UDM_SETPOS32 = 0x0471,
	_WM_CAP_DRIVER_GET_VERSIONW = 0x0471,
	_PSM_SETCURSELID = 0x0472,
	_UDM_GETPOS32 = 0x0472,
	_PSM_SETFINISHTEXTA = 0x0473,
	_PSM_GETTABCONTROL = 0x0474,
	_PSM_ISDIALOGMESSAGE = 0x0475,
	_MCIWNDM_REALIZE = 0x0476,
	_PSM_GETCURRENTPAGEHWND = 0x0476,
	_MCIWNDM_SETTIMEFORMATA = 0x0477,
	_PSM_INSERTPAGE = 0x0477,
	_EM_SETLANGOPTIONS = 0x0478,
	_MCIWNDM_GETTIMEFORMATA = 0x0478,
	_PSM_SETTITLEW = 0x0478,
	_WM_CAP_FILE_SET_CAPTURE_FILEW = 0x0478,
	_EM_GETLANGOPTIONS = 0x0479,
	_MCIWNDM_VALIDATEMEDIA = 0x0479,
	_PSM_SETFINISHTEXTW = 0x0479,
	_WM_CAP_FILE_GET_CAPTURE_FILEW = 0x0479,
	_EM_GETIMECOMPMODE = 0x047a,
	_EM_FINDTEXTW = 0x047b,
	_MCIWNDM_PLAYTO = 0x047b,
	_WM_CAP_FILE_SAVEASW = 0x047b,
	_EM_FINDTEXTEXW = 0x047c,
	_MCIWNDM_GETFILENAMEA = 0x047c,
	_EM_RECONVERSION = 0x047d,
	_MCIWNDM_GETDEVICEA = 0x047d,
	_PSM_SETHEADERTITLEA = 0x047d,
	_WM_CAP_FILE_SAVEDIBW = 0x047d,
	_EM_SETIMEMODEBIAS = 0x047e,
	_MCIWNDM_GETPALETTE = 0x047e,
	_PSM_SETHEADERTITLEW = 0x047e,
	_EM_GETIMEMODEBIAS = 0x047f,
	_MCIWNDM_SETPALETTE = 0x047f,
	_PSM_SETHEADERSUBTITLEA = 0x047f,
	_MCIWNDM_GETERRORA = 0x0480,
	_PSM_SETHEADERSUBTITLEW = 0x0480,
	_PSM_HWNDTOINDEX = 0x0481,
	_PSM_INDEXTOHWND = 0x0482,
	_MCIWNDM_SETINACTIVETIMER = 0x0483,
	_PSM_PAGETOINDEX = 0x0483,
	_PSM_INDEXTOPAGE = 0x0484,
	_DL_BEGINDRAG = 0x0485,
	_MCIWNDM_GETINACTIVETIMER = 0x0485,
	_PSM_IDTOINDEX = 0x0485,
	_DL_DRAGGING = 0x0486,
	_PSM_INDEXTOID = 0x0486,
	_DL_DROPPED = 0x0487,
	_PSM_GETRESULT = 0x0487,
	_DL_CANCELDRAG = 0x0488,
	_PSM_RECALCPAGESIZES = 0x0488,
	_MCIWNDM_GET_SOURCE = 0x048c,
	_MCIWNDM_PUT_SOURCE = 0x048d,
	_MCIWNDM_GET_DEST = 0x048e,
	_MCIWNDM_PUT_DEST = 0x048f,
	_MCIWNDM_CAN_PLAY = 0x0490,
	_MCIWNDM_CAN_WINDOW = 0x0491,
	_MCIWNDM_CAN_RECORD = 0x0492,
	_MCIWNDM_CAN_SAVE = 0x0493,
	_MCIWNDM_CAN_EJECT = 0x0494,
	_MCIWNDM_CAN_CONFIG = 0x0495,
	_IE_GETINK = 0x0496,
	_IE_MSGFIRST = 0x0496,
	_MCIWNDM_PALETTEKICK = 0x0496,
	_IE_SETINK = 0x0497,
	_IE_GETPENTIP = 0x0498,
	_IE_SETPENTIP = 0x0499,
	_IE_GETERASERTIP = 0x049a,
	_IE_SETERASERTIP = 0x049b,
	_IE_GETBKGND = 0x049c,
	_IE_SETBKGND = 0x049d,
	_IE_GETGRIDORIGIN = 0x049e,
	_IE_SETGRIDORIGIN = 0x049f,
	_IE_GETGRIDPEN = 0x04a0,
	_IE_SETGRIDPEN = 0x04a1,
	_IE_GETGRIDSIZE = 0x04a2,
	_IE_SETGRIDSIZE = 0x04a3,
	_IE_GETMODE = 0x04a4,
	_IE_SETMODE = 0x04a5,
	_IE_GETINKRECT = 0x04a6,
	_WM_CAP_SET_MCI_DEVICEW = 0x04a6,
	_WM_CAP_GET_MCI_DEVICEW = 0x04a7,
	_WM_CAP_PAL_OPENW = 0x04b4,
	_WM_CAP_PAL_SAVEW = 0x04b5,
	_IE_GETAPPDATA = 0x04b8,
	_IE_SETAPPDATA = 0x04b9,
	_IE_GETDRAWOPTS = 0x04ba,
	_IE_SETDRAWOPTS = 0x04bb,
	_IE_GETFORMAT = 0x04bc,
	_IE_SETFORMAT = 0x04bd,
	_IE_GETINKINPUT = 0x04be,
	_IE_SETINKINPUT = 0x04bf,
	_IE_GETNOTIFY = 0x04c0,
	_IE_SETNOTIFY = 0x04c1,
	_IE_GETRECOG = 0x04c2,
	_IE_SETRECOG = 0x04c3,
	_IE_GETSECURITY = 0x04c4,
	_IE_SETSECURITY = 0x04c5,
	_IE_GETSEL = 0x04c6,
	_IE_SETSEL = 0x04c7,
	_CDM_LAST = 0x04c8,
	_EM_SETBIDIOPTIONS = 0x04c8,
	_IE_DOCOMMAND = 0x04c8,
	_MCIWNDM_NOTIFYMODE = 0x04c8,
	_EM_GETBIDIOPTIONS = 0x04c9,
	_IE_GETCOMMAND = 0x04c9,
	_EM_SETTYPOGRAPHYOPTIONS = 0x04ca,
	_IE_GETCOUNT = 0x04ca,
	_EM_GETTYPOGRAPHYOPTIONS = 0x04cb,
	_IE_GETGESTURE = 0x04cb,
	_MCIWNDM_NOTIFYMEDIA = 0x04cb,
	_EM_SETEDITSTYLE = 0x04cc,
	_IE_GETMENU = 0x04cc,
	_EM_GETEDITSTYLE = 0x04cd,
	_IE_GETPAINTDC = 0x04cd,
	_MCIWNDM_NOTIFYERROR = 0x04cd,
	_IE_GETPDEVENT = 0x04ce,
	_IE_GETSELCOUNT = 0x04cf,
	_IE_GETSELITEMS = 0x04d0,
	_IE_GETSTYLE = 0x04d1,
	_MCIWNDM_SETTIMEFORMATW = 0x04db,
	_EM_OUTLINE = 0x04dc,
	_MCIWNDM_GETTIMEFORMATW = 0x04dc,
	_EM_GETSCROLLPOS = 0x04dd,
	_EM_SETSCROLLPOS = 0x04de,
	_EM_SETFONTSIZE = 0x04df,
	_EM_GETZOOM = 0x04e0,
	_MCIWNDM_GETFILENAMEW = 0x04e0,
	_EM_SETZOOM = 0x04e1,
	_MCIWNDM_GETDEVICEW = 0x04e1,
	_EM_GETVIEWKIND = 0x04e2,
	_EM_SETVIEWKIND = 0x04e3,
	_EM_GETPAGE = 0x04e4,
	_MCIWNDM_GETERRORW = 0x04e4,
	_EM_SETPAGE = 0x04e5,
	_EM_GETHYPHENATEINFO = 0x04e6,
	_EM_SETHYPHENATEINFO = 0x04e7,
	_EM_GETPAGEROTATE = 0x04eb,
	_EM_SETPAGEROTATE = 0x04ec,
	_EM_GETCTFMODEBIAS = 0x04ed,
	_EM_SETCTFMODEBIAS = 0x04ee,
	_EM_GETCTFOPENSTATUS = 0x04f0,
	_EM_SETCTFOPENSTATUS = 0x04f1,
	_EM_GETIMECOMPTEXT = 0x04f2,
	_EM_ISIME = 0x04f3,
	_EM_GETIMEPROPERTY = 0x04f4,
	_EM_GETQUERYRTFOBJ = 0x050d,
	_EM_SETQUERYRTFOBJ = 0x050e,
	_FM_GETFOCUS = 0x0600,
	_FM_GETDRIVEINFOA = 0x0601,
	_FM_GETSELCOUNT = 0x0602,
	_FM_GETSELCOUNTLFN = 0x0603,
	_FM_GETFILESELA = 0x0604,
	_FM_GETFILESELLFNA = 0x0605,
	_FM_REFRESH_WINDOWS = 0x0606,
	_FM_RELOAD_EXTENSIONS = 0x0607,
	_FM_GETDRIVEINFOW = 0x0611,
	_FM_GETFILESELW = 0x0614,
	_FM_GETFILESELLFNW = 0x0615,
	_WLX_WM_SAS = 0x0659,
	_SM_GETSELCOUNT = 0x07e8,
	_UM_GETSELCOUNT = 0x07e8,
	_WM_CPL_LAUNCH = 0x07e8,
	_SM_GETSERVERSELA = 0x07e9,
	_UM_GETUSERSELA = 0x07e9,
	_WM_CPL_LAUNCHED = 0x07e9,
	_SM_GETSERVERSELW = 0x07ea,
	_UM_GETUSERSELW = 0x07ea,
	_SM_GETCURFOCUSA = 0x07eb,
	_UM_GETGROUPSELA = 0x07eb,
	_SM_GETCURFOCUSW = 0x07ec,
	_UM_GETGROUPSELW = 0x07ec,
	_SM_GETOPTIONS = 0x07ed,
	_UM_GETCURFOCUSA = 0x07ed,
	_UM_GETCURFOCUSW = 0x07ee,
	_UM_GETOPTIONS = 0x07ef,
	_UM_GETOPTIONS2 = 0x07f0,
	_LVM_FIRST = 0x1000,
	_LVM_GETBKCOLOR = 0x1000,
	_LVM_SETBKCOLOR = 0x1001,
	_LVM_GETIMAGELIST = 0x1002,
	_LVM_SETIMAGELIST = 0x1003,
	_LVM_GETITEMCOUNT = 0x1004,
	_LVM_GETITEMA = 0x1005,
	_LVM_SETITEMA = 0x1006,
	_LVM_INSERTITEMA = 0x1007,
	_LVM_DELETEITEM = 0x1008,
	_LVM_DELETEALLITEMS = 0x1009,
	_LVM_GETCALLBACKMASK = 0x100a,
	_LVM_SETCALLBACKMASK = 0x100b,
	_LVM_GETNEXTITEM = 0x100c,
	_LVM_FINDITEMA = 0x100d,
	_LVM_GETITEMRECT = 0x100e,
	_LVM_SETITEMPOSITION = 0x100f,
	_LVM_GETITEMPOSITION = 0x1010,
	_LVM_GETSTRINGWIDTHA = 0x1011,
	_LVM_HITTEST = 0x1012,
	_LVM_ENSUREVISIBLE = 0x1013,
	_LVM_SCROLL = 0x1014,
	_LVM_REDRAWITEMS = 0x1015,
	_LVM_ARRANGE = 0x1016,
	_LVM_EDITLABELA = 0x1017,
	_LVM_GETEDITCONTROL = 0x1018,
	_LVM_GETCOLUMNA = 0x1019,
	_LVM_SETCOLUMNA = 0x101a,
	_LVM_INSERTCOLUMNA = 0x101b,
	_LVM_DELETECOLUMN = 0x101c,
	_LVM_GETCOLUMNWIDTH = 0x101d,
	_LVM_SETCOLUMNWIDTH = 0x101e,
	_LVM_GETHEADER = 0x101f,
	_LVM_CREATEDRAGIMAGE = 0x1021,
	_LVM_GETVIEWRECT = 0x1022,
	_LVM_GETTEXTCOLOR = 0x1023,
	_LVM_SETTEXTCOLOR = 0x1024,
	_LVM_GETTEXTBKCOLOR = 0x1025,
	_LVM_SETTEXTBKCOLOR = 0x1026,
	_LVM_GETTOPINDEX = 0x1027,
	_LVM_GETCOUNTPERPAGE = 0x1028,
	_LVM_GETORIGIN = 0x1029,
	_LVM_UPDATE = 0x102a,
	_LVM_SETITEMSTATE = 0x102b,
	_LVM_GETITEMSTATE = 0x102c,
	_LVM_GETITEMTEXTA = 0x102d,
	_LVM_SETITEMTEXTA = 0x102e,
	_LVM_SETITEMCOUNT = 0x102f,
	_LVM_SORTITEMS = 0x1030,
	_LVM_SETITEMPOSITION32 = 0x1031,
	_LVM_GETSELECTEDCOUNT = 0x1032,
	_LVM_GETITEMSPACING = 0x1033,
	_LVM_GETISEARCHSTRINGA = 0x1034,
	_LVM_SETICONSPACING = 0x1035,
	_LVM_SETEXTENDEDLISTVIEWSTYLE = 0x1036,
	_LVM_GETEXTENDEDLISTVIEWSTYLE = 0x1037,
	_LVM_GETSUBITEMRECT = 0x1038,
	_LVM_SUBITEMHITTEST = 0x1039,
	_LVM_SETCOLUMNORDERARRAY = 0x103a,
	_LVM_GETCOLUMNORDERARRAY = 0x103b,
	_LVM_SETHOTITEM = 0x103c,
	_LVM_GETHOTITEM = 0x103d,
	_LVM_SETHOTCURSOR = 0x103e,
	_LVM_GETHOTCURSOR = 0x103f,
	_LVM_APPROXIMATEVIEWRECT = 0x1040,
	_LVM_SETWORKAREAS = 0x1041,
	_LVM_GETSELECTIONMARK = 0x1042,
	_LVM_SETSELECTIONMARK = 0x1043,
	_LVM_SETBKIMAGEA = 0x1044,
	_LVM_GETBKIMAGEA = 0x1045,
	_LVM_GETWORKAREAS = 0x1046,
	_LVM_SETHOVERTIME = 0x1047,
	_LVM_GETHOVERTIME = 0x1048,
	_LVM_GETNUMBEROFWORKAREAS = 0x1049,
	_LVM_SETTOOLTIPS = 0x104a,
	_LVM_GETITEMW = 0x104b,
	_LVM_SETITEMW = 0x104c,
	_LVM_INSERTITEMW = 0x104d,
	_LVM_GETTOOLTIPS = 0x104e,
	_LVM_FINDITEMW = 0x1053,
	_LVM_GETSTRINGWIDTHW = 0x1057,
	_LVM_GETCOLUMNW = 0x105f,
	_LVM_SETCOLUMNW = 0x1060,
	_LVM_INSERTCOLUMNW = 0x1061,
	_LVM_GETITEMTEXTW = 0x1073,
	_LVM_SETITEMTEXTW = 0x1074,
	_LVM_GETISEARCHSTRINGW = 0x1075,
	_LVM_EDITLABELW = 0x1076,
	_LVM_GETBKIMAGEW = 0x108b,
	_LVM_SETSELECTEDCOLUMN = 0x108c,
	_LVM_SETTILEWIDTH = 0x108d,
	_LVM_SETVIEW = 0x108e,
	_LVM_GETVIEW = 0x108f,
	_LVM_INSERTGROUP = 0x1091,
	_LVM_SETGROUPINFO = 0x1093,
	_LVM_GETGROUPINFO = 0x1095,
	_LVM_REMOVEGROUP = 0x1096,
	_LVM_MOVEGROUP = 0x1097,
	_LVM_MOVEITEMTOGROUP = 0x109a,
	_LVM_SETGROUPMETRICS = 0x109b,
	_LVM_GETGROUPMETRICS = 0x109c,
	_LVM_ENABLEGROUPVIEW = 0x109d,
	_LVM_SORTGROUPS = 0x109e,
	_LVM_INSERTGROUPSORTED = 0x109f,
	_LVM_REMOVEALLGROUPS = 0x10a0,
	_LVM_HASGROUP = 0x10a1,
	_LVM_SETTILEVIEWINFO = 0x10a2,
	_LVM_GETTILEVIEWINFO = 0x10a3,
	_LVM_SETTILEINFO = 0x10a4,
	_LVM_GETTILEINFO = 0x10a5,
	_LVM_SETINSERTMARK = 0x10a6,
	_LVM_GETINSERTMARK = 0x10a7,
	_LVM_INSERTMARKHITTEST = 0x10a8,
	_LVM_GETINSERTMARKRECT = 0x10a9,
	_LVM_SETINSERTMARKCOLOR = 0x10aa,
	_LVM_GETINSERTMARKCOLOR = 0x10ab,
	_LVM_SETINFOTIP = 0x10ad,
	_LVM_GETSELECTEDCOLUMN = 0x10ae,
	_LVM_ISGROUPVIEWENABLED = 0x10af,
	_LVM_GETOUTLINECOLOR = 0x10b0,
	_LVM_SETOUTLINECOLOR = 0x10b1,
	_LVM_CANCELEDITLABEL = 0x10b3,
	_LVM_MAPINDEXTOID = 0x10b4,
	_LVM_MAPIDTOINDEX = 0x10b5,
	_LVM_ISITEMVISIBLE = 0x10b6,
	_LVM_GETEMPTYTEXT = 0x10cc,
	_LVM_GETFOOTERRECT = 0x10cd,
	_LVM_GETFOOTERINFO = 0x10ce,
	_LVM_GETFOOTERITEMRECT = 0x10cf,
	_LVM_GETFOOTERITEM = 0x10d0,
	_LVM_GETITEMINDEXRECT = 0x10d1,
	_LVM_SETITEMINDEXSTATE = 0x10d2,
	_LVM_GETNEXTITEMINDEX = 0x10d3,
	_CCM_FIRST = 0x2000,
	_OCM__BASE = 0x2000,
	_CCM_SETBKCOLOR = 0x2001,
	_CCM_SETCOLORSCHEME = 0x2002,
	_CCM_GETCOLORSCHEME = 0x2003,
	_CCM_GETDROPTARGET = 0x2004,
	_CCM_SETUNICODEFORMAT = 0x2005,
	_LVM_SETUNICODEFORMAT = 0x2005,
	_CCM_GETUNICODEFORMAT = 0x2006,
	_LVM_GETUNICODEFORMAT = 0x2006,
	_CCM_SETVERSION = 0x2007,
	_CCM_GETVERSION = 0x2008,
	_CCM_SETNOTIFYWINDOW = 0x2009,
	_CCM_SETWINDOWTHEME = 0x200b,
	_CCM_DPISCALE = 0x200c,
	_OCM_CTLCOLOR = 0x2019,
	_OCM_DRAWITEM = 0x202b,
	_OCM_MEASUREITEM = 0x202c,
	_OCM_DELETEITEM = 0x202d,
	_OCM_VKEYTOITEM = 0x202e,
	_OCM_CHARTOITEM = 0x202f,
	_OCM_COMPAREITEM = 0x2039,
	_OCM_NOTIFY = 0x204e,
	_OCM_COMMAND = 0x2111,
	_OCM_HSCROLL = 0x2114,
	_OCM_VSCROLL = 0x2115,
	_OCM_CTLCOLORMSGBOX = 0x2132,
	_OCM_CTLCOLOREDIT = 0x2133,
	_OCM_CTLCOLORLISTBOX = 0x2134,
	_OCM_CTLCOLORBTN = 0x2135,
	_OCM_CTLCOLORDLG = 0x2136,
	_OCM_CTLCOLORSCROLLBAR = 0x2137,
	_OCM_CTLCOLORSTATIC = 0x2138,
	_OCM_PARENTNOTIFY = 0x2200,
	_WM_APP = 0x8000,
	_WM_RASDIALEVENT = 0xcccd,
};
REFLECT(WindowsMessageCode) {
	ENUM_VALUE(_WM_NULL);
	ENUM_VALUE(_WM_CREATE);
	ENUM_VALUE(_WM_DESTROY);
	ENUM_VALUE(_WM_MOVE);
	ENUM_VALUE(_WM_SIZE);
	ENUM_VALUE(_WM_ACTIVATE);
	ENUM_VALUE(_WM_SETFOCUS);
	ENUM_VALUE(_WM_KILLFOCUS);
	ENUM_VALUE(_WM_ENABLE);
	ENUM_VALUE(_WM_SETREDRAW);
	ENUM_VALUE(_WM_SETTEXT);
	ENUM_VALUE(_WM_GETTEXT);
	ENUM_VALUE(_WM_GETTEXTLENGTH);
	ENUM_VALUE(_WM_PAINT);
	ENUM_VALUE(_WM_CLOSE);
	ENUM_VALUE(_WM_QUERYENDSESSION);
	ENUM_VALUE(_WM_QUIT);
	ENUM_VALUE(_WM_QUERYOPEN);
	ENUM_VALUE(_WM_ERASEBKGND);
	ENUM_VALUE(_WM_SYSCOLORCHANGE);
	ENUM_VALUE(_WM_ENDSESSION);
	ENUM_VALUE(_WM_SHOWWINDOW);
	ENUM_VALUE(_WM_CTLCOLOR);
	ENUM_VALUE(_WM_WININICHANGE);
	ENUM_VALUE(_WM_DEVMODECHANGE);
	ENUM_VALUE(_WM_ACTIVATEAPP);
	ENUM_VALUE(_WM_FONTCHANGE);
	ENUM_VALUE(_WM_TIMECHANGE);
	ENUM_VALUE(_WM_CANCELMODE);
	ENUM_VALUE(_WM_SETCURSOR);
	ENUM_VALUE(_WM_MOUSEACTIVATE);
	ENUM_VALUE(_WM_CHILDACTIVATE);
	ENUM_VALUE(_WM_QUEUESYNC);
	ENUM_VALUE(_WM_GETMINMAXINFO);
	ENUM_VALUE(_WM_PAINTICON);
	ENUM_VALUE(_WM_ICONERASEBKGND);
	ENUM_VALUE(_WM_NEXTDLGCTL);
	ENUM_VALUE(_WM_SPOOLERSTATUS);
	ENUM_VALUE(_WM_DRAWITEM);
	ENUM_VALUE(_WM_MEASUREITEM);
	ENUM_VALUE(_WM_DELETEITEM);
	ENUM_VALUE(_WM_VKEYTOITEM);
	ENUM_VALUE(_WM_CHARTOITEM);
	ENUM_VALUE(_WM_SETFONT);
	ENUM_VALUE(_WM_GETFONT);
	ENUM_VALUE(_WM_SETHOTKEY);
	ENUM_VALUE(_WM_GETHOTKEY);
	ENUM_VALUE(_WM_QUERYDRAGICON);
	ENUM_VALUE(_WM_COMPAREITEM);
	ENUM_VALUE(_WM_GETOBJECT);
	ENUM_VALUE(_WM_COMPACTING);
	ENUM_VALUE(_WM_COMMNOTIFY);
	ENUM_VALUE(_WM_WINDOWPOSCHANGING);
	ENUM_VALUE(_WM_WINDOWPOSCHANGED);
	ENUM_VALUE(_WM_POWER);
	ENUM_VALUE(_WM_COPYGLOBALDATA);
	ENUM_VALUE(_WM_COPYDATA);
	ENUM_VALUE(_WM_CANCELJOURNAL);
	ENUM_VALUE(_WM_NOTIFY);
	ENUM_VALUE(_WM_INPUTLANGCHANGEREQUEST);
	ENUM_VALUE(_WM_INPUTLANGCHANGE);
	ENUM_VALUE(_WM_TCARD);
	ENUM_VALUE(_WM_HELP);
	ENUM_VALUE(_WM_USERCHANGED);
	ENUM_VALUE(_WM_NOTIFYFORMAT);
	ENUM_VALUE(_WM_CONTEXTMENU);
	ENUM_VALUE(_WM_STYLECHANGING);
	ENUM_VALUE(_WM_STYLECHANGED);
	ENUM_VALUE(_WM_DISPLAYCHANGE);
	ENUM_VALUE(_WM_GETICON);
	ENUM_VALUE(_WM_SETICON);
	ENUM_VALUE(_WM_NCCREATE);
	ENUM_VALUE(_WM_NCDESTROY);
	ENUM_VALUE(_WM_NCCALCSIZE);
	ENUM_VALUE(_WM_NCHITTEST);
	ENUM_VALUE(_WM_NCPAINT);
	ENUM_VALUE(_WM_NCACTIVATE);
	ENUM_VALUE(_WM_GETDLGCODE);
	ENUM_VALUE(_WM_SYNCPAINT);
	ENUM_VALUE(_WM_NCMOUSEMOVE);
	ENUM_VALUE(_WM_NCLBUTTONDOWN);
	ENUM_VALUE(_WM_NCLBUTTONUP);
	ENUM_VALUE(_WM_NCLBUTTONDBLCLK);
	ENUM_VALUE(_WM_NCRBUTTONDOWN);
	ENUM_VALUE(_WM_NCRBUTTONUP);
	ENUM_VALUE(_WM_NCRBUTTONDBLCLK);
	ENUM_VALUE(_WM_NCMBUTTONDOWN);
	ENUM_VALUE(_WM_NCMBUTTONUP);
	ENUM_VALUE(_WM_NCMBUTTONDBLCLK);
	ENUM_VALUE(_WM_NCXBUTTONDOWN);
	ENUM_VALUE(_WM_NCXBUTTONUP);
	ENUM_VALUE(_WM_NCXBUTTONDBLCLK);
	ENUM_VALUE(_EM_GETSEL);
	ENUM_VALUE(_EM_SETSEL);
	ENUM_VALUE(_EM_GETRECT);
	ENUM_VALUE(_EM_SETRECT);
	ENUM_VALUE(_EM_SETRECTNP);
	ENUM_VALUE(_EM_SCROLL);
	ENUM_VALUE(_EM_LINESCROLL);
	ENUM_VALUE(_EM_SCROLLCARET);
	ENUM_VALUE(_EM_GETMODIFY);
	ENUM_VALUE(_EM_SETMODIFY);
	ENUM_VALUE(_EM_GETLINECOUNT);
	ENUM_VALUE(_EM_LINEINDEX);
	ENUM_VALUE(_EM_SETHANDLE);
	ENUM_VALUE(_EM_GETHANDLE);
	ENUM_VALUE(_EM_GETTHUMB);
	ENUM_VALUE(_EM_LINELENGTH);
	ENUM_VALUE(_EM_REPLACESEL);
	ENUM_VALUE(_EM_SETFONT);
	ENUM_VALUE(_EM_GETLINE);
	ENUM_VALUE(_EM_LIMITTEXT);
	ENUM_VALUE(_EM_SETLIMITTEXT);
	ENUM_VALUE(_EM_CANUNDO);
	ENUM_VALUE(_EM_UNDO);
	ENUM_VALUE(_EM_FMTLINES);
	ENUM_VALUE(_EM_LINEFROMCHAR);
	ENUM_VALUE(_EM_SETWORDBREAK);
	ENUM_VALUE(_EM_SETTABSTOPS);
	ENUM_VALUE(_EM_SETPASSWORDCHAR);
	ENUM_VALUE(_EM_EMPTYUNDOBUFFER);
	ENUM_VALUE(_EM_GETFIRSTVISIBLELINE);
	ENUM_VALUE(_EM_SETREADONLY);
	ENUM_VALUE(_EM_SETWORDBREAKPROC);
	ENUM_VALUE(_EM_GETWORDBREAKPROC);
	ENUM_VALUE(_EM_GETPASSWORDCHAR);
	ENUM_VALUE(_EM_SETMARGINS);
	ENUM_VALUE(_EM_GETMARGINS);
	ENUM_VALUE(_EM_GETLIMITTEXT);
	ENUM_VALUE(_EM_POSFROMCHAR);
	ENUM_VALUE(_EM_CHARFROMPOS);
	ENUM_VALUE(_EM_SETIMESTATUS);
	ENUM_VALUE(_EM_GETIMESTATUS);
	ENUM_VALUE(_SBM_SETPOS);
	ENUM_VALUE(_SBM_GETPOS);
	ENUM_VALUE(_SBM_SETRANGE);
	ENUM_VALUE(_SBM_GETRANGE);
	ENUM_VALUE(_SBM_ENABLE_ARROWS);
	ENUM_VALUE(_SBM_SETRANGEREDRAW);
	ENUM_VALUE(_SBM_SETSCROLLINFO);
	ENUM_VALUE(_SBM_GETSCROLLINFO);
	ENUM_VALUE(_SBM_GETSCROLLBARINFO);
	ENUM_VALUE(_BM_GETCHECK);
	ENUM_VALUE(_BM_SETCHECK);
	ENUM_VALUE(_BM_GETSTATE);
	ENUM_VALUE(_BM_SETSTATE);
	ENUM_VALUE(_BM_SETSTYLE);
	ENUM_VALUE(_BM_CLICK);
	ENUM_VALUE(_BM_GETIMAGE);
	ENUM_VALUE(_BM_SETIMAGE);
	ENUM_VALUE(_BM_SETDONTCLICK);
	ENUM_VALUE(_WM_INPUT);
	ENUM_VALUE(_WM_KEYDOWN);
	ENUM_VALUE(_WM_KEYFIRST);
	ENUM_VALUE(_WM_KEYUP);
	ENUM_VALUE(_WM_CHAR);
	ENUM_VALUE(_WM_DEADCHAR);
	ENUM_VALUE(_WM_SYSKEYDOWN);
	ENUM_VALUE(_WM_SYSKEYUP);
	ENUM_VALUE(_WM_SYSCHAR);
	ENUM_VALUE(_WM_SYSDEADCHAR);
	ENUM_VALUE(_WM_UNICHAR);
	ENUM_VALUE(_WM_WNT_CONVERTREQUESTEX);
	ENUM_VALUE(_WM_CONVERTREQUEST);
	ENUM_VALUE(_WM_CONVERTRESULT);
	ENUM_VALUE(_WM_INTERIM);
	ENUM_VALUE(_WM_IME_STARTCOMPOSITION);
	ENUM_VALUE(_WM_IME_ENDCOMPOSITION);
	ENUM_VALUE(_WM_IME_COMPOSITION);
	ENUM_VALUE(_WM_IME_KEYLAST);
	ENUM_VALUE(_WM_INITDIALOG);
	ENUM_VALUE(_WM_COMMAND);
	ENUM_VALUE(_WM_SYSCOMMAND);
	ENUM_VALUE(_WM_TIMER);
	ENUM_VALUE(_WM_HSCROLL);
	ENUM_VALUE(_WM_VSCROLL);
	ENUM_VALUE(_WM_INITMENU);
	ENUM_VALUE(_WM_INITMENUPOPUP);
	ENUM_VALUE(_WM_SYSTIMER);
	ENUM_VALUE(_WM_MENUSELECT);
	ENUM_VALUE(_WM_MENUCHAR);
	ENUM_VALUE(_WM_ENTERIDLE);
	ENUM_VALUE(_WM_MENURBUTTONUP);
	ENUM_VALUE(_WM_MENUDRAG);
	ENUM_VALUE(_WM_MENUGETOBJECT);
	ENUM_VALUE(_WM_UNINITMENUPOPUP);
	ENUM_VALUE(_WM_MENUCOMMAND);
	ENUM_VALUE(_WM_CHANGEUISTATE);
	ENUM_VALUE(_WM_UPDATEUISTATE);
	ENUM_VALUE(_WM_QUERYUISTATE);
	ENUM_VALUE(_WM_LBTRACKPOINT);
	ENUM_VALUE(_WM_CTLCOLORMSGBOX);
	ENUM_VALUE(_WM_CTLCOLOREDIT);
	ENUM_VALUE(_WM_CTLCOLORLISTBOX);
	ENUM_VALUE(_WM_CTLCOLORBTN);
	ENUM_VALUE(_WM_CTLCOLORDLG);
	ENUM_VALUE(_WM_CTLCOLORSCROLLBAR);
	ENUM_VALUE(_WM_CTLCOLORSTATIC);
	ENUM_VALUE(_CB_GETEDITSEL);
	ENUM_VALUE(_CB_LIMITTEXT);
	ENUM_VALUE(_CB_SETEDITSEL);
	ENUM_VALUE(_CB_ADDSTRING);
	ENUM_VALUE(_CB_DELETESTRING);
	ENUM_VALUE(_CB_DIR);
	ENUM_VALUE(_CB_GETCOUNT);
	ENUM_VALUE(_CB_GETCURSEL);
	ENUM_VALUE(_CB_GETLBTEXT);
	ENUM_VALUE(_CB_GETLBTEXTLEN);
	ENUM_VALUE(_CB_INSERTSTRING);
	ENUM_VALUE(_CB_RESETCONTENT);
	ENUM_VALUE(_CB_FINDSTRING);
	ENUM_VALUE(_CB_SELECTSTRING);
	ENUM_VALUE(_CB_SETCURSEL);
	ENUM_VALUE(_CB_SHOWDROPDOWN);
	ENUM_VALUE(_CB_GETITEMDATA);
	ENUM_VALUE(_CB_SETITEMDATA);
	ENUM_VALUE(_CB_GETDROPPEDCONTROLRECT);
	ENUM_VALUE(_CB_SETITEMHEIGHT);
	ENUM_VALUE(_CB_GETITEMHEIGHT);
	ENUM_VALUE(_CB_SETEXTENDEDUI);
	ENUM_VALUE(_CB_GETEXTENDEDUI);
	ENUM_VALUE(_CB_GETDROPPEDSTATE);
	ENUM_VALUE(_CB_FINDSTRINGEXACT);
	ENUM_VALUE(_CB_SETLOCALE);
	ENUM_VALUE(_CB_GETLOCALE);
	ENUM_VALUE(_CB_GETTOPINDEX);
	ENUM_VALUE(_CB_SETTOPINDEX);
	ENUM_VALUE(_CB_GETHORIZONTALEXTENT);
	ENUM_VALUE(_CB_SETHORIZONTALEXTENT);
	ENUM_VALUE(_CB_GETDROPPEDWIDTH);
	ENUM_VALUE(_CB_SETDROPPEDWIDTH);
	ENUM_VALUE(_CB_INITSTORAGE);
	ENUM_VALUE(_CB_MULTIPLEADDSTRING);
	ENUM_VALUE(_CB_GETCOMBOBOXINFO);
	ENUM_VALUE(_CB_MSGMAX);
	ENUM_VALUE(_WM_MOUSEFIRST);
	ENUM_VALUE(_WM_MOUSEMOVE);
	ENUM_VALUE(_WM_LBUTTONDOWN);
	ENUM_VALUE(_WM_LBUTTONUP);
	ENUM_VALUE(_WM_LBUTTONDBLCLK);
	ENUM_VALUE(_WM_RBUTTONDOWN);
	ENUM_VALUE(_WM_RBUTTONUP);
	ENUM_VALUE(_WM_RBUTTONDBLCLK);
	ENUM_VALUE(_WM_MBUTTONDOWN);
	ENUM_VALUE(_WM_MBUTTONUP);
	ENUM_VALUE(_WM_MBUTTONDBLCLK);
	ENUM_VALUE(_WM_MOUSELAST);
	ENUM_VALUE(_WM_MOUSEWHEEL);
	ENUM_VALUE(_WM_XBUTTONDOWN);
	ENUM_VALUE(_WM_XBUTTONUP);
	ENUM_VALUE(_WM_XBUTTONDBLCLK);
	ENUM_VALUE(_WM_MOUSEHWHEEL);
	ENUM_VALUE(_WM_PARENTNOTIFY);
	ENUM_VALUE(_WM_ENTERMENULOOP);
	ENUM_VALUE(_WM_EXITMENULOOP);
	ENUM_VALUE(_WM_NEXTMENU);
	ENUM_VALUE(_WM_SIZING);
	ENUM_VALUE(_WM_CAPTURECHANGED);
	ENUM_VALUE(_WM_MOVING);
	ENUM_VALUE(_WM_POWERBROADCAST);
	ENUM_VALUE(_WM_DEVICECHANGE);
	ENUM_VALUE(_WM_MDICREATE);
	ENUM_VALUE(_WM_MDIDESTROY);
	ENUM_VALUE(_WM_MDIACTIVATE);
	ENUM_VALUE(_WM_MDIRESTORE);
	ENUM_VALUE(_WM_MDINEXT);
	ENUM_VALUE(_WM_MDIMAXIMIZE);
	ENUM_VALUE(_WM_MDITILE);
	ENUM_VALUE(_WM_MDICASCADE);
	ENUM_VALUE(_WM_MDIICONARRANGE);
	ENUM_VALUE(_WM_MDIGETACTIVE);
	ENUM_VALUE(_WM_MDISETMENU);
	ENUM_VALUE(_WM_ENTERSIZEMOVE);
	ENUM_VALUE(_WM_EXITSIZEMOVE);
	ENUM_VALUE(_WM_DROPFILES);
	ENUM_VALUE(_WM_MDIREFRESHMENU);
	ENUM_VALUE(_WM_IME_REPORT);
	ENUM_VALUE(_WM_IME_SETCONTEXT);
	ENUM_VALUE(_WM_IME_NOTIFY);
	ENUM_VALUE(_WM_IME_CONTROL);
	ENUM_VALUE(_WM_IME_COMPOSITIONFULL);
	ENUM_VALUE(_WM_IME_SELECT);
	ENUM_VALUE(_WM_IME_CHAR);
	ENUM_VALUE(_WM_IME_REQUEST);
	ENUM_VALUE(_WM_IMEKEYDOWN);
	ENUM_VALUE(_WM_IME_KEYDOWN);
	ENUM_VALUE(_WM_IMEKEYUP);
	ENUM_VALUE(_WM_IME_KEYUP);
	ENUM_VALUE(_WM_NCMOUSEHOVER);
	ENUM_VALUE(_WM_MOUSEHOVER);
	ENUM_VALUE(_WM_NCMOUSELEAVE);
	ENUM_VALUE(_WM_MOUSELEAVE);
	ENUM_VALUE(_WM_CUT);
	ENUM_VALUE(_WM_COPY);
	ENUM_VALUE(_WM_PASTE);
	ENUM_VALUE(_WM_CLEAR);
	ENUM_VALUE(_WM_UNDO);
	ENUM_VALUE(_WM_RENDERFORMAT);
	ENUM_VALUE(_WM_RENDERALLFORMATS);
	ENUM_VALUE(_WM_DESTROYCLIPBOARD);
	ENUM_VALUE(_WM_DRAWCLIPBOARD);
	ENUM_VALUE(_WM_PAINTCLIPBOARD);
	ENUM_VALUE(_WM_VSCROLLCLIPBOARD);
	ENUM_VALUE(_WM_SIZECLIPBOARD);
	ENUM_VALUE(_WM_ASKCBFORMATNAME);
	ENUM_VALUE(_WM_CHANGECBCHAIN);
	ENUM_VALUE(_WM_HSCROLLCLIPBOARD);
	ENUM_VALUE(_WM_QUERYNEWPALETTE);
	ENUM_VALUE(_WM_PALETTEISCHANGING);
	ENUM_VALUE(_WM_PALETTECHANGED);
	ENUM_VALUE(_WM_HOTKEY);
	ENUM_VALUE(_WM_PRINT);
	ENUM_VALUE(_WM_PRINTCLIENT);
	ENUM_VALUE(_WM_APPCOMMAND);
	ENUM_VALUE(_WM_HANDHELDFIRST);
	ENUM_VALUE(_WM_HANDHELDLAST);
	ENUM_VALUE(_WM_AFXFIRST);
	ENUM_VALUE(_WM_AFXLAST);
	ENUM_VALUE(_WM_PENWINFIRST);
	ENUM_VALUE(_WM_RCRESULT);
	ENUM_VALUE(_WM_HOOKRCRESULT);
	ENUM_VALUE(_WM_GLOBALRCCHANGE);
	ENUM_VALUE(_WM_PENMISCINFO);
	ENUM_VALUE(_WM_SKB);
	ENUM_VALUE(_WM_HEDITCTL);
	ENUM_VALUE(_WM_PENCTL);
	ENUM_VALUE(_WM_PENMISC);
	ENUM_VALUE(_WM_CTLINIT);
	ENUM_VALUE(_WM_PENEVENT);
	ENUM_VALUE(_WM_PENWINLAST);
	ENUM_VALUE(_DDM_SETFMT);
	ENUM_VALUE(_DM_GETDEFID);
	ENUM_VALUE(_NIN_SELECT);
	ENUM_VALUE(_TBM_GETPOS);
	ENUM_VALUE(_WM_PSD_PAGESETUPDLG);
	ENUM_VALUE(_WM_USER);
	ENUM_VALUE(_CBEM_INSERTITEMA);
	ENUM_VALUE(_DDM_DRAW);
	ENUM_VALUE(_DM_SETDEFID);
	ENUM_VALUE(_HKM_SETHOTKEY);
	ENUM_VALUE(_PBM_SETRANGE);
	ENUM_VALUE(_RB_INSERTBANDA);
	ENUM_VALUE(_SB_SETTEXTA);
	ENUM_VALUE(_TB_ENABLEBUTTON);
	ENUM_VALUE(_TBM_GETRANGEMIN);
	ENUM_VALUE(_TTM_ACTIVATE);
	ENUM_VALUE(_WM_CHOOSEFONT_GETLOGFONT);
	ENUM_VALUE(_WM_PSD_FULLPAGERECT);
	ENUM_VALUE(_CBEM_SETIMAGELIST);
	ENUM_VALUE(_DDM_CLOSE);
	ENUM_VALUE(_DM_REPOSITION);
	ENUM_VALUE(_HKM_GETHOTKEY);
	ENUM_VALUE(_PBM_SETPOS);
	ENUM_VALUE(_RB_DELETEBAND);
	ENUM_VALUE(_SB_GETTEXTA);
	ENUM_VALUE(_TB_CHECKBUTTON);
	ENUM_VALUE(_TBM_GETRANGEMAX);
	ENUM_VALUE(_WM_PSD_MINMARGINRECT);
	ENUM_VALUE(_CBEM_GETIMAGELIST);
	ENUM_VALUE(_DDM_BEGIN);
	ENUM_VALUE(_HKM_SETRULES);
	ENUM_VALUE(_PBM_DELTAPOS);
	ENUM_VALUE(_RB_GETBARINFO);
	ENUM_VALUE(_SB_GETTEXTLENGTHA);
	ENUM_VALUE(_TBM_GETTIC);
	ENUM_VALUE(_TB_PRESSBUTTON);
	ENUM_VALUE(_TTM_SETDELAYTIME);
	ENUM_VALUE(_WM_PSD_MARGINRECT);
	ENUM_VALUE(_CBEM_GETITEMA);
	ENUM_VALUE(_DDM_END);
	ENUM_VALUE(_PBM_SETSTEP);
	ENUM_VALUE(_RB_SETBARINFO);
	ENUM_VALUE(_SB_SETPARTS);
	ENUM_VALUE(_TB_HIDEBUTTON);
	ENUM_VALUE(_TBM_SETTIC);
	ENUM_VALUE(_TTM_ADDTOOLA);
	ENUM_VALUE(_WM_PSD_GREEKTEXTRECT);
	ENUM_VALUE(_CBEM_SETITEMA);
	ENUM_VALUE(_PBM_STEPIT);
	ENUM_VALUE(_TB_INDETERMINATE);
	ENUM_VALUE(_TBM_SETPOS);
	ENUM_VALUE(_TTM_DELTOOLA);
	ENUM_VALUE(_WM_PSD_ENVSTAMPRECT);
	ENUM_VALUE(_CBEM_GETCOMBOCONTROL);
	ENUM_VALUE(_PBM_SETRANGE32);
	ENUM_VALUE(_RB_SETBANDINFOA);
	ENUM_VALUE(_SB_GETPARTS);
	ENUM_VALUE(_TB_MARKBUTTON);
	ENUM_VALUE(_TBM_SETRANGE);
	ENUM_VALUE(_TTM_NEWTOOLRECTA);
	ENUM_VALUE(_WM_PSD_YAFULLPAGERECT);
	ENUM_VALUE(_CBEM_GETEDITCONTROL);
	ENUM_VALUE(_PBM_GETRANGE);
	ENUM_VALUE(_RB_SETPARENT);
	ENUM_VALUE(_SB_GETBORDERS);
	ENUM_VALUE(_TBM_SETRANGEMIN);
	ENUM_VALUE(_TTM_RELAYEVENT);
	ENUM_VALUE(_CBEM_SETEXSTYLE);
	ENUM_VALUE(_PBM_GETPOS);
	ENUM_VALUE(_RB_HITTEST);
	ENUM_VALUE(_SB_SETMINHEIGHT);
	ENUM_VALUE(_TBM_SETRANGEMAX);
	ENUM_VALUE(_TTM_GETTOOLINFOA);
	ENUM_VALUE(_CBEM_GETEXSTYLE);
	ENUM_VALUE(_CBEM_GETEXTENDEDSTYLE);
	ENUM_VALUE(_PBM_SETBARCOLOR);
	ENUM_VALUE(_RB_GETRECT);
	ENUM_VALUE(_SB_SIMPLE);
	ENUM_VALUE(_TB_ISBUTTONENABLED);
	ENUM_VALUE(_TBM_CLEARTICS);
	ENUM_VALUE(_TTM_SETTOOLINFOA);
	ENUM_VALUE(_CBEM_HASEDITCHANGED);
	ENUM_VALUE(_RB_INSERTBANDW);
	ENUM_VALUE(_SB_GETRECT);
	ENUM_VALUE(_TB_ISBUTTONCHECKED);
	ENUM_VALUE(_TBM_SETSEL);
	ENUM_VALUE(_TTM_HITTESTA);
	ENUM_VALUE(_WIZ_QUERYNUMPAGES);
	ENUM_VALUE(_CBEM_INSERTITEMW);
	ENUM_VALUE(_RB_SETBANDINFOW);
	ENUM_VALUE(_SB_SETTEXTW);
	ENUM_VALUE(_TB_ISBUTTONPRESSED);
	ENUM_VALUE(_TBM_SETSELSTART);
	ENUM_VALUE(_TTM_GETTEXTA);
	ENUM_VALUE(_WIZ_NEXT);
	ENUM_VALUE(_CBEM_SETITEMW);
	ENUM_VALUE(_RB_GETBANDCOUNT);
	ENUM_VALUE(_SB_GETTEXTLENGTHW);
	ENUM_VALUE(_TB_ISBUTTONHIDDEN);
	ENUM_VALUE(_TBM_SETSELEND);
	ENUM_VALUE(_TTM_UPDATETIPTEXTA);
	ENUM_VALUE(_WIZ_PREV);
	ENUM_VALUE(_CBEM_GETITEMW);
	ENUM_VALUE(_RB_GETROWCOUNT);
	ENUM_VALUE(_SB_GETTEXTW);
	ENUM_VALUE(_TB_ISBUTTONINDETERMINATE);
	ENUM_VALUE(_TTM_GETTOOLCOUNT);
	ENUM_VALUE(_CBEM_SETEXTENDEDSTYLE);
	ENUM_VALUE(_RB_GETROWHEIGHT);
	ENUM_VALUE(_SB_ISSIMPLE);
	ENUM_VALUE(_TB_ISBUTTONHIGHLIGHTED);
	ENUM_VALUE(_TBM_GETPTICS);
	ENUM_VALUE(_TTM_ENUMTOOLSA);
	ENUM_VALUE(_SB_SETICON);
	ENUM_VALUE(_TBM_GETTICPOS);
	ENUM_VALUE(_TTM_GETCURRENTTOOLA);
	ENUM_VALUE(_RB_IDTOINDEX);
	ENUM_VALUE(_SB_SETTIPTEXTA);
	ENUM_VALUE(_TBM_GETNUMTICS);
	ENUM_VALUE(_TTM_WINDOWFROMPOINT);
	ENUM_VALUE(_RB_GETTOOLTIPS);
	ENUM_VALUE(_SB_SETTIPTEXTW);
	ENUM_VALUE(_TBM_GETSELSTART);
	ENUM_VALUE(_TB_SETSTATE);
	ENUM_VALUE(_TTM_TRACKACTIVATE);
	ENUM_VALUE(_RB_SETTOOLTIPS);
	ENUM_VALUE(_SB_GETTIPTEXTA);
	ENUM_VALUE(_TB_GETSTATE);
	ENUM_VALUE(_TBM_GETSELEND);
	ENUM_VALUE(_TTM_TRACKPOSITION);
	ENUM_VALUE(_RB_SETBKCOLOR);
	ENUM_VALUE(_SB_GETTIPTEXTW);
	ENUM_VALUE(_TB_ADDBITMAP);
	ENUM_VALUE(_TBM_CLEARSEL);
	ENUM_VALUE(_TTM_SETTIPBKCOLOR);
	ENUM_VALUE(_RB_GETBKCOLOR);
	ENUM_VALUE(_SB_GETICON);
	ENUM_VALUE(_TB_ADDBUTTONSA);
	ENUM_VALUE(_TBM_SETTICFREQ);
	ENUM_VALUE(_TTM_SETTIPTEXTCOLOR);
	ENUM_VALUE(_RB_SETTEXTCOLOR);
	ENUM_VALUE(_TB_INSERTBUTTONA);
	ENUM_VALUE(_TBM_SETPAGESIZE);
	ENUM_VALUE(_TTM_GETDELAYTIME);
	ENUM_VALUE(_RB_GETTEXTCOLOR);
	ENUM_VALUE(_TB_DELETEBUTTON);
	ENUM_VALUE(_TBM_GETPAGESIZE);
	ENUM_VALUE(_TTM_GETTIPBKCOLOR);
	ENUM_VALUE(_RB_SIZETORECT);
	ENUM_VALUE(_TB_GETBUTTON);
	ENUM_VALUE(_TBM_SETLINESIZE);
	ENUM_VALUE(_TTM_GETTIPTEXTCOLOR);
	ENUM_VALUE(_RB_BEGINDRAG);
	ENUM_VALUE(_TB_BUTTONCOUNT);
	ENUM_VALUE(_TBM_GETLINESIZE);
	ENUM_VALUE(_TTM_SETMAXTIPWIDTH);
	ENUM_VALUE(_RB_ENDDRAG);
	ENUM_VALUE(_TB_COMMANDTOINDEX);
	ENUM_VALUE(_TBM_GETTHUMBRECT);
	ENUM_VALUE(_TTM_GETMAXTIPWIDTH);
	ENUM_VALUE(_RB_DRAGMOVE);
	ENUM_VALUE(_TBM_GETCHANNELRECT);
	ENUM_VALUE(_TB_SAVERESTOREA);
	ENUM_VALUE(_TTM_SETMARGIN);
	ENUM_VALUE(_RB_GETBARHEIGHT);
	ENUM_VALUE(_TB_CUSTOMIZE);
	ENUM_VALUE(_TBM_SETTHUMBLENGTH);
	ENUM_VALUE(_TTM_GETMARGIN);
	ENUM_VALUE(_RB_GETBANDINFOW);
	ENUM_VALUE(_TB_ADDSTRINGA);
	ENUM_VALUE(_TBM_GETTHUMBLENGTH);
	ENUM_VALUE(_TTM_POP);
	ENUM_VALUE(_RB_GETBANDINFOA);
	ENUM_VALUE(_TB_GETITEMRECT);
	ENUM_VALUE(_TBM_SETTOOLTIPS);
	ENUM_VALUE(_TTM_UPDATE);
	ENUM_VALUE(_RB_MINIMIZEBAND);
	ENUM_VALUE(_TB_BUTTONSTRUCTSIZE);
	ENUM_VALUE(_TBM_GETTOOLTIPS);
	ENUM_VALUE(_TTM_GETBUBBLESIZE);
	ENUM_VALUE(_RB_MAXIMIZEBAND);
	ENUM_VALUE(_TBM_SETTIPSIDE);
	ENUM_VALUE(_TB_SETBUTTONSIZE);
	ENUM_VALUE(_TTM_ADJUSTRECT);
	ENUM_VALUE(_TBM_SETBUDDY);
	ENUM_VALUE(_TB_SETBITMAPSIZE);
	ENUM_VALUE(_TTM_SETTITLEA);
	ENUM_VALUE(_MSG_FTS_JUMP_VA);
	ENUM_VALUE(_TB_AUTOSIZE);
	ENUM_VALUE(_TBM_GETBUDDY);
	ENUM_VALUE(_TTM_SETTITLEW);
	ENUM_VALUE(_RB_GETBANDBORDERS);
	ENUM_VALUE(_MSG_FTS_JUMP_QWORD);
	ENUM_VALUE(_RB_SHOWBAND);
	ENUM_VALUE(_TB_GETTOOLTIPS);
	ENUM_VALUE(_MSG_REINDEX_REQUEST);
	ENUM_VALUE(_TB_SETTOOLTIPS);
	ENUM_VALUE(_MSG_FTS_WHERE_IS_IT);
	ENUM_VALUE(_RB_SETPALETTE);
	ENUM_VALUE(_TB_SETPARENT);
	ENUM_VALUE(_RB_GETPALETTE);
	ENUM_VALUE(_RB_MOVEBAND);
	ENUM_VALUE(_TB_SETROWS);
	ENUM_VALUE(_TB_GETROWS);
	ENUM_VALUE(_TB_GETBITMAPFLAGS);
	ENUM_VALUE(_TB_SETCMDID);
	ENUM_VALUE(_RB_PUSHCHEVRON);
	ENUM_VALUE(_TB_CHANGEBITMAP);
	ENUM_VALUE(_TB_GETBITMAP);
	ENUM_VALUE(_MSG_GET_DEFFONT);
	ENUM_VALUE(_TB_GETBUTTONTEXTA);
	ENUM_VALUE(_TB_REPLACEBITMAP);
	ENUM_VALUE(_TB_SETINDENT);
	ENUM_VALUE(_TB_SETIMAGELIST);
	ENUM_VALUE(_TB_GETIMAGELIST);
	ENUM_VALUE(_TB_LOADIMAGES);
	ENUM_VALUE(_EM_CANPASTE);
	ENUM_VALUE(_TTM_ADDTOOLW);
	ENUM_VALUE(_EM_DISPLAYBAND);
	ENUM_VALUE(_TB_GETRECT);
	ENUM_VALUE(_TTM_DELTOOLW);
	ENUM_VALUE(_EM_EXGETSEL);
	ENUM_VALUE(_TB_SETHOTIMAGELIST);
	ENUM_VALUE(_TTM_NEWTOOLRECTW);
	ENUM_VALUE(_EM_EXLIMITTEXT);
	ENUM_VALUE(_TB_GETHOTIMAGELIST);
	ENUM_VALUE(_TTM_GETTOOLINFOW);
	ENUM_VALUE(_EM_EXLINEFROMCHAR);
	ENUM_VALUE(_TB_SETDISABLEDIMAGELIST);
	ENUM_VALUE(_TTM_SETTOOLINFOW);
	ENUM_VALUE(_EM_EXSETSEL);
	ENUM_VALUE(_TB_GETDISABLEDIMAGELIST);
	ENUM_VALUE(_TTM_HITTESTW);
	ENUM_VALUE(_EM_FINDTEXT);
	ENUM_VALUE(_TB_SETSTYLE);
	ENUM_VALUE(_TTM_GETTEXTW);
	ENUM_VALUE(_EM_FORMATRANGE);
	ENUM_VALUE(_TB_GETSTYLE);
	ENUM_VALUE(_TTM_UPDATETIPTEXTW);
	ENUM_VALUE(_EM_GETCHARFORMAT);
	ENUM_VALUE(_TB_GETBUTTONSIZE);
	ENUM_VALUE(_TTM_ENUMTOOLSW);
	ENUM_VALUE(_EM_GETEVENTMASK);
	ENUM_VALUE(_TB_SETBUTTONWIDTH);
	ENUM_VALUE(_TTM_GETCURRENTTOOLW);
	ENUM_VALUE(_EM_GETOLEINTERFACE);
	ENUM_VALUE(_TB_SETMAXTEXTROWS);
	ENUM_VALUE(_EM_GETPARAFORMAT);
	ENUM_VALUE(_TB_GETTEXTROWS);
	ENUM_VALUE(_EM_GETSELTEXT);
	ENUM_VALUE(_TB_GETOBJECT);
	ENUM_VALUE(_EM_HIDESELECTION);
	ENUM_VALUE(_TB_GETBUTTONINFOW);
	ENUM_VALUE(_EM_PASTESPECIAL);
	ENUM_VALUE(_TB_SETBUTTONINFOW);
	ENUM_VALUE(_EM_REQUESTRESIZE);
	ENUM_VALUE(_TB_GETBUTTONINFOA);
	ENUM_VALUE(_EM_SELECTIONTYPE);
	ENUM_VALUE(_TB_SETBUTTONINFOA);
	ENUM_VALUE(_EM_SETBKGNDCOLOR);
	ENUM_VALUE(_TB_INSERTBUTTONW);
	ENUM_VALUE(_EM_SETCHARFORMAT);
	ENUM_VALUE(_TB_ADDBUTTONSW);
	ENUM_VALUE(_EM_SETEVENTMASK);
	ENUM_VALUE(_TB_HITTEST);
	ENUM_VALUE(_EM_SETOLECALLBACK);
	ENUM_VALUE(_TB_SETDRAWTEXTFLAGS);
	ENUM_VALUE(_EM_SETPARAFORMAT);
	ENUM_VALUE(_TB_GETHOTITEM);
	ENUM_VALUE(_EM_SETTARGETDEVICE);
	ENUM_VALUE(_TB_SETHOTITEM);
	ENUM_VALUE(_EM_STREAMIN);
	ENUM_VALUE(_TB_SETANCHORHIGHLIGHT);
	ENUM_VALUE(_EM_STREAMOUT);
	ENUM_VALUE(_TB_GETANCHORHIGHLIGHT);
	ENUM_VALUE(_EM_GETTEXTRANGE);
	ENUM_VALUE(_TB_GETBUTTONTEXTW);
	ENUM_VALUE(_EM_FINDWORDBREAK);
	ENUM_VALUE(_TB_SAVERESTOREW);
	ENUM_VALUE(_EM_SETOPTIONS);
	ENUM_VALUE(_TB_ADDSTRINGW);
	ENUM_VALUE(_EM_GETOPTIONS);
	ENUM_VALUE(_TB_MAPACCELERATORA);
	ENUM_VALUE(_EM_FINDTEXTEX);
	ENUM_VALUE(_TB_GETINSERTMARK);
	ENUM_VALUE(_EM_GETWORDBREAKPROCEX);
	ENUM_VALUE(_TB_SETINSERTMARK);
	ENUM_VALUE(_EM_SETWORDBREAKPROCEX);
	ENUM_VALUE(_TB_INSERTMARKHITTEST);
	ENUM_VALUE(_EM_SETUNDOLIMIT);
	ENUM_VALUE(_TB_MOVEBUTTON);
	ENUM_VALUE(_TB_GETMAXSIZE);
	ENUM_VALUE(_EM_REDO);
	ENUM_VALUE(_TB_SETEXTENDEDSTYLE);
	ENUM_VALUE(_EM_CANREDO);
	ENUM_VALUE(_TB_GETEXTENDEDSTYLE);
	ENUM_VALUE(_EM_GETUNDONAME);
	ENUM_VALUE(_TB_GETPADDING);
	ENUM_VALUE(_EM_GETREDONAME);
	ENUM_VALUE(_TB_SETPADDING);
	ENUM_VALUE(_EM_STOPGROUPTYPING);
	ENUM_VALUE(_TB_SETINSERTMARKCOLOR);
	ENUM_VALUE(_EM_SETTEXTMODE);
	ENUM_VALUE(_TB_GETINSERTMARKCOLOR);
	ENUM_VALUE(_EM_GETTEXTMODE);
	ENUM_VALUE(_TB_MAPACCELERATORW);
	ENUM_VALUE(_EM_AUTOURLDETECT);
	ENUM_VALUE(_TB_GETSTRINGW);
	ENUM_VALUE(_EM_GETAUTOURLDETECT);
	ENUM_VALUE(_TB_GETSTRINGA);
	ENUM_VALUE(_EM_SETPALETTE);
	ENUM_VALUE(_EM_GETTEXTEX);
	ENUM_VALUE(_EM_GETTEXTLENGTHEX);
	ENUM_VALUE(_EM_SHOWSCROLLBAR);
	ENUM_VALUE(_EM_SETTEXTEX);
	ENUM_VALUE(_TAPI_REPLY);
	ENUM_VALUE(_ACM_OPENA);
	ENUM_VALUE(_BFFM_SETSTATUSTEXTA);
	ENUM_VALUE(_CDM_FIRST);
	ENUM_VALUE(_CDM_GETSPEC);
	ENUM_VALUE(_EM_SETPUNCTUATION);
	ENUM_VALUE(_IPM_CLEARADDRESS);
	ENUM_VALUE(_WM_CAP_UNICODE_START);
	ENUM_VALUE(_ACM_PLAY);
	ENUM_VALUE(_BFFM_ENABLEOK);
	ENUM_VALUE(_CDM_GETFILEPATH);
	ENUM_VALUE(_EM_GETPUNCTUATION);
	ENUM_VALUE(_IPM_SETADDRESS);
	ENUM_VALUE(_PSM_SETCURSEL);
	ENUM_VALUE(_UDM_SETRANGE);
	ENUM_VALUE(_WM_CHOOSEFONT_SETLOGFONT);
	ENUM_VALUE(_ACM_STOP);
	ENUM_VALUE(_BFFM_SETSELECTIONA);
	ENUM_VALUE(_CDM_GETFOLDERPATH);
	ENUM_VALUE(_EM_SETWORDWRAPMODE);
	ENUM_VALUE(_IPM_GETADDRESS);
	ENUM_VALUE(_PSM_REMOVEPAGE);
	ENUM_VALUE(_UDM_GETRANGE);
	ENUM_VALUE(_WM_CAP_SET_CALLBACK_ERRORW);
	ENUM_VALUE(_WM_CHOOSEFONT_SETFLAGS);
	ENUM_VALUE(_ACM_OPENW);
	ENUM_VALUE(_BFFM_SETSELECTIONW);
	ENUM_VALUE(_CDM_GETFOLDERIDLIST);
	ENUM_VALUE(_EM_GETWORDWRAPMODE);
	ENUM_VALUE(_IPM_SETRANGE);
	ENUM_VALUE(_PSM_ADDPAGE);
	ENUM_VALUE(_UDM_SETPOS);
	ENUM_VALUE(_WM_CAP_SET_CALLBACK_STATUSW);
	ENUM_VALUE(_BFFM_SETSTATUSTEXTW);
	ENUM_VALUE(_CDM_SETCONTROLTEXT);
	ENUM_VALUE(_EM_SETIMECOLOR);
	ENUM_VALUE(_IPM_SETFOCUS);
	ENUM_VALUE(_PSM_CHANGED);
	ENUM_VALUE(_UDM_GETPOS);
	ENUM_VALUE(_CDM_HIDECONTROL);
	ENUM_VALUE(_EM_GETIMECOLOR);
	ENUM_VALUE(_IPM_ISBLANK);
	ENUM_VALUE(_PSM_RESTARTWINDOWS);
	ENUM_VALUE(_UDM_SETBUDDY);
	ENUM_VALUE(_CDM_SETDEFEXT);
	ENUM_VALUE(_EM_SETIMEOPTIONS);
	ENUM_VALUE(_PSM_REBOOTSYSTEM);
	ENUM_VALUE(_UDM_GETBUDDY);
	ENUM_VALUE(_EM_GETIMEOPTIONS);
	ENUM_VALUE(_PSM_CANCELTOCLOSE);
	ENUM_VALUE(_UDM_SETACCEL);
	ENUM_VALUE(_EM_CONVPOSITION);
	ENUM_VALUE(_MCIWNDM_GETZOOM);
	ENUM_VALUE(_PSM_UNCHANGED);
	ENUM_VALUE(_UDM_SETBASE);
	ENUM_VALUE(_PSM_APPLY);
	ENUM_VALUE(_UDM_GETBASE);
	ENUM_VALUE(_PSM_SETTITLEA);
	ENUM_VALUE(_UDM_SETRANGE32);
	ENUM_VALUE(_PSM_SETWIZBUTTONS);
	ENUM_VALUE(_UDM_GETRANGE32);
	ENUM_VALUE(_WM_CAP_DRIVER_GET_NAMEW);
	ENUM_VALUE(_PSM_PRESSBUTTON);
	ENUM_VALUE(_UDM_SETPOS32);
	ENUM_VALUE(_WM_CAP_DRIVER_GET_VERSIONW);
	ENUM_VALUE(_PSM_SETCURSELID);
	ENUM_VALUE(_UDM_GETPOS32);
	ENUM_VALUE(_PSM_SETFINISHTEXTA);
	ENUM_VALUE(_PSM_GETTABCONTROL);
	ENUM_VALUE(_PSM_ISDIALOGMESSAGE);
	ENUM_VALUE(_MCIWNDM_REALIZE);
	ENUM_VALUE(_PSM_GETCURRENTPAGEHWND);
	ENUM_VALUE(_MCIWNDM_SETTIMEFORMATA);
	ENUM_VALUE(_PSM_INSERTPAGE);
	ENUM_VALUE(_EM_SETLANGOPTIONS);
	ENUM_VALUE(_MCIWNDM_GETTIMEFORMATA);
	ENUM_VALUE(_PSM_SETTITLEW);
	ENUM_VALUE(_WM_CAP_FILE_SET_CAPTURE_FILEW);
	ENUM_VALUE(_EM_GETLANGOPTIONS);
	ENUM_VALUE(_MCIWNDM_VALIDATEMEDIA);
	ENUM_VALUE(_PSM_SETFINISHTEXTW);
	ENUM_VALUE(_WM_CAP_FILE_GET_CAPTURE_FILEW);
	ENUM_VALUE(_EM_GETIMECOMPMODE);
	ENUM_VALUE(_EM_FINDTEXTW);
	ENUM_VALUE(_MCIWNDM_PLAYTO);
	ENUM_VALUE(_WM_CAP_FILE_SAVEASW);
	ENUM_VALUE(_EM_FINDTEXTEXW);
	ENUM_VALUE(_MCIWNDM_GETFILENAMEA);
	ENUM_VALUE(_EM_RECONVERSION);
	ENUM_VALUE(_MCIWNDM_GETDEVICEA);
	ENUM_VALUE(_PSM_SETHEADERTITLEA);
	ENUM_VALUE(_WM_CAP_FILE_SAVEDIBW);
	ENUM_VALUE(_EM_SETIMEMODEBIAS);
	ENUM_VALUE(_MCIWNDM_GETPALETTE);
	ENUM_VALUE(_PSM_SETHEADERTITLEW);
	ENUM_VALUE(_EM_GETIMEMODEBIAS);
	ENUM_VALUE(_MCIWNDM_SETPALETTE);
	ENUM_VALUE(_PSM_SETHEADERSUBTITLEA);
	ENUM_VALUE(_MCIWNDM_GETERRORA);
	ENUM_VALUE(_PSM_SETHEADERSUBTITLEW);
	ENUM_VALUE(_PSM_HWNDTOINDEX);
	ENUM_VALUE(_PSM_INDEXTOHWND);
	ENUM_VALUE(_MCIWNDM_SETINACTIVETIMER);
	ENUM_VALUE(_PSM_PAGETOINDEX);
	ENUM_VALUE(_PSM_INDEXTOPAGE);
	ENUM_VALUE(_DL_BEGINDRAG);
	ENUM_VALUE(_MCIWNDM_GETINACTIVETIMER);
	ENUM_VALUE(_PSM_IDTOINDEX);
	ENUM_VALUE(_DL_DRAGGING);
	ENUM_VALUE(_PSM_INDEXTOID);
	ENUM_VALUE(_DL_DROPPED);
	ENUM_VALUE(_PSM_GETRESULT);
	ENUM_VALUE(_DL_CANCELDRAG);
	ENUM_VALUE(_PSM_RECALCPAGESIZES);
	ENUM_VALUE(_MCIWNDM_GET_SOURCE);
	ENUM_VALUE(_MCIWNDM_PUT_SOURCE);
	ENUM_VALUE(_MCIWNDM_GET_DEST);
	ENUM_VALUE(_MCIWNDM_PUT_DEST);
	ENUM_VALUE(_MCIWNDM_CAN_PLAY);
	ENUM_VALUE(_MCIWNDM_CAN_WINDOW);
	ENUM_VALUE(_MCIWNDM_CAN_RECORD);
	ENUM_VALUE(_MCIWNDM_CAN_SAVE);
	ENUM_VALUE(_MCIWNDM_CAN_EJECT);
	ENUM_VALUE(_MCIWNDM_CAN_CONFIG);
	ENUM_VALUE(_IE_GETINK);
	ENUM_VALUE(_IE_MSGFIRST);
	ENUM_VALUE(_MCIWNDM_PALETTEKICK);
	ENUM_VALUE(_IE_SETINK);
	ENUM_VALUE(_IE_GETPENTIP);
	ENUM_VALUE(_IE_SETPENTIP);
	ENUM_VALUE(_IE_GETERASERTIP);
	ENUM_VALUE(_IE_SETERASERTIP);
	ENUM_VALUE(_IE_GETBKGND);
	ENUM_VALUE(_IE_SETBKGND);
	ENUM_VALUE(_IE_GETGRIDORIGIN);
	ENUM_VALUE(_IE_SETGRIDORIGIN);
	ENUM_VALUE(_IE_GETGRIDPEN);
	ENUM_VALUE(_IE_SETGRIDPEN);
	ENUM_VALUE(_IE_GETGRIDSIZE);
	ENUM_VALUE(_IE_SETGRIDSIZE);
	ENUM_VALUE(_IE_GETMODE);
	ENUM_VALUE(_IE_SETMODE);
	ENUM_VALUE(_IE_GETINKRECT);
	ENUM_VALUE(_WM_CAP_SET_MCI_DEVICEW);
	ENUM_VALUE(_WM_CAP_GET_MCI_DEVICEW);
	ENUM_VALUE(_WM_CAP_PAL_OPENW);
	ENUM_VALUE(_WM_CAP_PAL_SAVEW);
	ENUM_VALUE(_IE_GETAPPDATA);
	ENUM_VALUE(_IE_SETAPPDATA);
	ENUM_VALUE(_IE_GETDRAWOPTS);
	ENUM_VALUE(_IE_SETDRAWOPTS);
	ENUM_VALUE(_IE_GETFORMAT);
	ENUM_VALUE(_IE_SETFORMAT);
	ENUM_VALUE(_IE_GETINKINPUT);
	ENUM_VALUE(_IE_SETINKINPUT);
	ENUM_VALUE(_IE_GETNOTIFY);
	ENUM_VALUE(_IE_SETNOTIFY);
	ENUM_VALUE(_IE_GETRECOG);
	ENUM_VALUE(_IE_SETRECOG);
	ENUM_VALUE(_IE_GETSECURITY);
	ENUM_VALUE(_IE_SETSECURITY);
	ENUM_VALUE(_IE_GETSEL);
	ENUM_VALUE(_IE_SETSEL);
	ENUM_VALUE(_CDM_LAST);
	ENUM_VALUE(_EM_SETBIDIOPTIONS);
	ENUM_VALUE(_IE_DOCOMMAND);
	ENUM_VALUE(_MCIWNDM_NOTIFYMODE);
	ENUM_VALUE(_EM_GETBIDIOPTIONS);
	ENUM_VALUE(_IE_GETCOMMAND);
	ENUM_VALUE(_EM_SETTYPOGRAPHYOPTIONS);
	ENUM_VALUE(_IE_GETCOUNT);
	ENUM_VALUE(_EM_GETTYPOGRAPHYOPTIONS);
	ENUM_VALUE(_IE_GETGESTURE);
	ENUM_VALUE(_MCIWNDM_NOTIFYMEDIA);
	ENUM_VALUE(_EM_SETEDITSTYLE);
	ENUM_VALUE(_IE_GETMENU);
	ENUM_VALUE(_EM_GETEDITSTYLE);
	ENUM_VALUE(_IE_GETPAINTDC);
	ENUM_VALUE(_MCIWNDM_NOTIFYERROR);
	ENUM_VALUE(_IE_GETPDEVENT);
	ENUM_VALUE(_IE_GETSELCOUNT);
	ENUM_VALUE(_IE_GETSELITEMS);
	ENUM_VALUE(_IE_GETSTYLE);
	ENUM_VALUE(_MCIWNDM_SETTIMEFORMATW);
	ENUM_VALUE(_EM_OUTLINE);
	ENUM_VALUE(_MCIWNDM_GETTIMEFORMATW);
	ENUM_VALUE(_EM_GETSCROLLPOS);
	ENUM_VALUE(_EM_SETSCROLLPOS);
	ENUM_VALUE(_EM_SETSCROLLPOS);
	ENUM_VALUE(_EM_SETFONTSIZE);
	ENUM_VALUE(_EM_GETZOOM);
	ENUM_VALUE(_MCIWNDM_GETFILENAMEW);
	ENUM_VALUE(_EM_SETZOOM);
	ENUM_VALUE(_MCIWNDM_GETDEVICEW);
	ENUM_VALUE(_EM_GETVIEWKIND);
	ENUM_VALUE(_EM_SETVIEWKIND);
	ENUM_VALUE(_EM_GETPAGE);
	ENUM_VALUE(_MCIWNDM_GETERRORW);
	ENUM_VALUE(_EM_SETPAGE);
	ENUM_VALUE(_EM_GETHYPHENATEINFO);
	ENUM_VALUE(_EM_SETHYPHENATEINFO);
	ENUM_VALUE(_EM_GETPAGEROTATE);
	ENUM_VALUE(_EM_SETPAGEROTATE);
	ENUM_VALUE(_EM_GETCTFMODEBIAS);
	ENUM_VALUE(_EM_SETCTFMODEBIAS);
	ENUM_VALUE(_EM_GETCTFOPENSTATUS);
	ENUM_VALUE(_EM_SETCTFOPENSTATUS);
	ENUM_VALUE(_EM_GETIMECOMPTEXT);
	ENUM_VALUE(_EM_ISIME);
	ENUM_VALUE(_EM_GETIMEPROPERTY);
	ENUM_VALUE(_EM_GETQUERYRTFOBJ);
	ENUM_VALUE(_EM_SETQUERYRTFOBJ);
	ENUM_VALUE(_FM_GETFOCUS);
	ENUM_VALUE(_FM_GETDRIVEINFOA);
	ENUM_VALUE(_FM_GETSELCOUNT);
	ENUM_VALUE(_FM_GETSELCOUNTLFN);
	ENUM_VALUE(_FM_GETFILESELA);
	ENUM_VALUE(_FM_GETFILESELLFNA);
	ENUM_VALUE(_FM_REFRESH_WINDOWS);
	ENUM_VALUE(_FM_RELOAD_EXTENSIONS);
	ENUM_VALUE(_FM_GETDRIVEINFOW);
	ENUM_VALUE(_FM_GETFILESELW);
	ENUM_VALUE(_FM_GETFILESELLFNW);
	ENUM_VALUE(_WLX_WM_SAS);
	ENUM_VALUE(_SM_GETSELCOUNT);
	ENUM_VALUE(_UM_GETSELCOUNT);
	ENUM_VALUE(_WM_CPL_LAUNCH);
	ENUM_VALUE(_SM_GETSERVERSELA);
	ENUM_VALUE(_UM_GETUSERSELA);
	ENUM_VALUE(_WM_CPL_LAUNCHED);
	ENUM_VALUE(_SM_GETSERVERSELW);
	ENUM_VALUE(_UM_GETUSERSELW);
	ENUM_VALUE(_SM_GETCURFOCUSA);
	ENUM_VALUE(_UM_GETGROUPSELA);
	ENUM_VALUE(_SM_GETCURFOCUSW);
	ENUM_VALUE(_UM_GETGROUPSELW);
	ENUM_VALUE(_SM_GETOPTIONS);
	ENUM_VALUE(_UM_GETCURFOCUSA);
	ENUM_VALUE(_UM_GETCURFOCUSW);
	ENUM_VALUE(_UM_GETOPTIONS);
	ENUM_VALUE(_UM_GETOPTIONS2);
	ENUM_VALUE(_LVM_FIRST);
	ENUM_VALUE(_LVM_GETBKCOLOR);
	ENUM_VALUE(_LVM_SETBKCOLOR);
	ENUM_VALUE(_LVM_GETIMAGELIST);
	ENUM_VALUE(_LVM_SETIMAGELIST);
	ENUM_VALUE(_LVM_GETITEMCOUNT);
	ENUM_VALUE(_LVM_GETITEMA);
	ENUM_VALUE(_LVM_SETITEMA);
	ENUM_VALUE(_LVM_INSERTITEMA);
	ENUM_VALUE(_LVM_DELETEITEM);
	ENUM_VALUE(_LVM_DELETEALLITEMS);
	ENUM_VALUE(_LVM_GETCALLBACKMASK);
	ENUM_VALUE(_LVM_SETCALLBACKMASK);
	ENUM_VALUE(_LVM_GETNEXTITEM);
	ENUM_VALUE(_LVM_FINDITEMA);
	ENUM_VALUE(_LVM_GETITEMRECT);
	ENUM_VALUE(_LVM_SETITEMPOSITION);
	ENUM_VALUE(_LVM_GETITEMPOSITION);
	ENUM_VALUE(_LVM_GETSTRINGWIDTHA);
	ENUM_VALUE(_LVM_HITTEST);
	ENUM_VALUE(_LVM_ENSUREVISIBLE);
	ENUM_VALUE(_LVM_SCROLL);
	ENUM_VALUE(_LVM_REDRAWITEMS);
	ENUM_VALUE(_LVM_ARRANGE);
	ENUM_VALUE(_LVM_EDITLABELA);
	ENUM_VALUE(_LVM_GETEDITCONTROL);
	ENUM_VALUE(_LVM_GETCOLUMNA);
	ENUM_VALUE(_LVM_SETCOLUMNA);
	ENUM_VALUE(_LVM_INSERTCOLUMNA);
	ENUM_VALUE(_LVM_DELETECOLUMN);
	ENUM_VALUE(_LVM_GETCOLUMNWIDTH);
	ENUM_VALUE(_LVM_SETCOLUMNWIDTH);
	ENUM_VALUE(_LVM_GETHEADER);
	ENUM_VALUE(_LVM_CREATEDRAGIMAGE);
	ENUM_VALUE(_LVM_GETVIEWRECT);
	ENUM_VALUE(_LVM_GETTEXTCOLOR);
	ENUM_VALUE(_LVM_SETTEXTCOLOR);
	ENUM_VALUE(_LVM_GETTEXTBKCOLOR);
	ENUM_VALUE(_LVM_SETTEXTBKCOLOR);
	ENUM_VALUE(_LVM_GETTOPINDEX);
	ENUM_VALUE(_LVM_GETCOUNTPERPAGE);
	ENUM_VALUE(_LVM_GETORIGIN);
	ENUM_VALUE(_LVM_UPDATE);
	ENUM_VALUE(_LVM_SETITEMSTATE);
	ENUM_VALUE(_LVM_GETITEMSTATE);
	ENUM_VALUE(_LVM_GETITEMTEXTA);
	ENUM_VALUE(_LVM_SETITEMTEXTA);
	ENUM_VALUE(_LVM_SETITEMCOUNT);
	ENUM_VALUE(_LVM_SORTITEMS);
	ENUM_VALUE(_LVM_SETITEMPOSITION32);
	ENUM_VALUE(_LVM_GETSELECTEDCOUNT);
	ENUM_VALUE(_LVM_GETITEMSPACING);
	ENUM_VALUE(_LVM_GETISEARCHSTRINGA);
	ENUM_VALUE(_LVM_SETICONSPACING);
	ENUM_VALUE(_LVM_SETEXTENDEDLISTVIEWSTYLE);
	ENUM_VALUE(_LVM_GETEXTENDEDLISTVIEWSTYLE);
	ENUM_VALUE(_LVM_GETSUBITEMRECT);
	ENUM_VALUE(_LVM_SUBITEMHITTEST);
	ENUM_VALUE(_LVM_SETCOLUMNORDERARRAY);
	ENUM_VALUE(_LVM_GETCOLUMNORDERARRAY);
	ENUM_VALUE(_LVM_SETHOTITEM);
	ENUM_VALUE(_LVM_GETHOTITEM);
	ENUM_VALUE(_LVM_SETHOTCURSOR);
	ENUM_VALUE(_LVM_GETHOTCURSOR);
	ENUM_VALUE(_LVM_APPROXIMATEVIEWRECT);
	ENUM_VALUE(_LVM_SETWORKAREAS);
	ENUM_VALUE(_LVM_GETSELECTIONMARK);
	ENUM_VALUE(_LVM_SETSELECTIONMARK);
	ENUM_VALUE(_LVM_SETBKIMAGEA);
	ENUM_VALUE(_LVM_GETBKIMAGEA);
	ENUM_VALUE(_LVM_GETWORKAREAS);
	ENUM_VALUE(_LVM_SETHOVERTIME);
	ENUM_VALUE(_LVM_GETHOVERTIME);
	ENUM_VALUE(_LVM_GETNUMBEROFWORKAREAS);
	ENUM_VALUE(_LVM_SETTOOLTIPS);
	ENUM_VALUE(_LVM_GETITEMW);
	ENUM_VALUE(_LVM_SETITEMW);
	ENUM_VALUE(_LVM_INSERTITEMW);
	ENUM_VALUE(_LVM_GETTOOLTIPS);
	ENUM_VALUE(_LVM_FINDITEMW);
	ENUM_VALUE(_LVM_GETSTRINGWIDTHW);
	ENUM_VALUE(_LVM_GETCOLUMNW);
	ENUM_VALUE(_LVM_SETCOLUMNW);
	ENUM_VALUE(_LVM_INSERTCOLUMNW);
	ENUM_VALUE(_LVM_GETITEMTEXTW);
	ENUM_VALUE(_LVM_SETITEMTEXTW);
	ENUM_VALUE(_LVM_GETISEARCHSTRINGW);
	ENUM_VALUE(_LVM_EDITLABELW);
	ENUM_VALUE(_LVM_GETBKIMAGEW);
	ENUM_VALUE(_LVM_SETSELECTEDCOLUMN);
	ENUM_VALUE(_LVM_SETTILEWIDTH);
	ENUM_VALUE(_LVM_SETVIEW);
	ENUM_VALUE(_LVM_GETVIEW);
	ENUM_VALUE(_LVM_INSERTGROUP);
	ENUM_VALUE(_LVM_SETGROUPINFO);
	ENUM_VALUE(_LVM_GETGROUPINFO);
	ENUM_VALUE(_LVM_REMOVEGROUP);
	ENUM_VALUE(_LVM_MOVEGROUP);
	ENUM_VALUE(_LVM_MOVEITEMTOGROUP);
	ENUM_VALUE(_LVM_SETGROUPMETRICS);
	ENUM_VALUE(_LVM_GETGROUPMETRICS);
	ENUM_VALUE(_LVM_ENABLEGROUPVIEW);
	ENUM_VALUE(_LVM_SORTGROUPS);
	ENUM_VALUE(_LVM_INSERTGROUPSORTED);
	ENUM_VALUE(_LVM_REMOVEALLGROUPS);
	ENUM_VALUE(_LVM_HASGROUP);
	ENUM_VALUE(_LVM_SETTILEVIEWINFO);
	ENUM_VALUE(_LVM_GETTILEVIEWINFO);
	ENUM_VALUE(_LVM_SETTILEINFO);
	ENUM_VALUE(_LVM_GETTILEINFO);
	ENUM_VALUE(_LVM_SETINSERTMARK);
	ENUM_VALUE(_LVM_GETINSERTMARK);
	ENUM_VALUE(_LVM_INSERTMARKHITTEST);
	ENUM_VALUE(_LVM_GETINSERTMARKRECT);
	ENUM_VALUE(_LVM_SETINSERTMARKCOLOR);
	ENUM_VALUE(_LVM_GETINSERTMARKCOLOR);
	ENUM_VALUE(_LVM_SETINFOTIP);
	ENUM_VALUE(_LVM_GETSELECTEDCOLUMN);
	ENUM_VALUE(_LVM_ISGROUPVIEWENABLED);
	ENUM_VALUE(_LVM_GETOUTLINECOLOR);
	ENUM_VALUE(_LVM_SETOUTLINECOLOR);
	ENUM_VALUE(_LVM_CANCELEDITLABEL);
	ENUM_VALUE(_LVM_MAPINDEXTOID);
	ENUM_VALUE(_LVM_MAPIDTOINDEX);
	ENUM_VALUE(_LVM_ISITEMVISIBLE);
	ENUM_VALUE(_LVM_GETEMPTYTEXT);
	ENUM_VALUE(_LVM_GETFOOTERRECT);
	ENUM_VALUE(_LVM_GETFOOTERINFO);
	ENUM_VALUE(_LVM_GETFOOTERITEMRECT);
	ENUM_VALUE(_LVM_GETFOOTERITEM);
	ENUM_VALUE(_LVM_GETITEMINDEXRECT);
	ENUM_VALUE(_LVM_SETITEMINDEXSTATE);
	ENUM_VALUE(_LVM_GETNEXTITEMINDEX);
	ENUM_VALUE(_CCM_FIRST);
	ENUM_VALUE(_OCM__BASE);
	ENUM_VALUE(_CCM_SETBKCOLOR);
	ENUM_VALUE(_CCM_SETCOLORSCHEME);
	ENUM_VALUE(_CCM_GETCOLORSCHEME);
	ENUM_VALUE(_CCM_GETDROPTARGET);
	ENUM_VALUE(_CCM_SETUNICODEFORMAT);
	ENUM_VALUE(_LVM_SETUNICODEFORMAT);
	ENUM_VALUE(_CCM_GETUNICODEFORMAT);
	ENUM_VALUE(_LVM_GETUNICODEFORMAT);
	ENUM_VALUE(_CCM_SETVERSION);
	ENUM_VALUE(_CCM_GETVERSION);
	ENUM_VALUE(_CCM_SETNOTIFYWINDOW);
	ENUM_VALUE(_CCM_SETWINDOWTHEME);
	ENUM_VALUE(_CCM_DPISCALE);
	ENUM_VALUE(_OCM_CTLCOLOR);
	ENUM_VALUE(_OCM_DRAWITEM);
	ENUM_VALUE(_OCM_MEASUREITEM);
	ENUM_VALUE(_OCM_DELETEITEM);
	ENUM_VALUE(_OCM_VKEYTOITEM);
	ENUM_VALUE(_OCM_CHARTOITEM);
	ENUM_VALUE(_OCM_COMPAREITEM);
	ENUM_VALUE(_OCM_NOTIFY);
	ENUM_VALUE(_OCM_COMMAND);
	ENUM_VALUE(_OCM_HSCROLL);
	ENUM_VALUE(_OCM_VSCROLL);
	ENUM_VALUE(_OCM_CTLCOLORMSGBOX);
	ENUM_VALUE(_OCM_CTLCOLOREDIT);
	ENUM_VALUE(_OCM_CTLCOLORLISTBOX);
	ENUM_VALUE(_OCM_CTLCOLORBTN);
	ENUM_VALUE(_OCM_CTLCOLORDLG);
	ENUM_VALUE(_OCM_CTLCOLORSCROLLBAR);
	ENUM_VALUE(_OCM_CTLCOLORSTATIC);
	ENUM_VALUE(_OCM_PARENTNOTIFY);
	ENUM_VALUE(_OCM_PARENTNOTIFY);
	ENUM_VALUE(_WM_APP);
	ENUM_VALUE(_WM_RASDIALEVENT);
}