name: test
on: [push]
jobs:
  run-test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Clang
        if: runner.os != 'macOS'
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
      - name: Install Windows SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Run test
        run: python3 test.py --verbose
